### PR TITLE
Update document

### PR DESCRIPTION
**Pull request by shijojoy**
Updated the document

### CODE REVIEW

**Comment by PRMerger20** [comment]
@shijojoy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shijojoy** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@shijojoy: I'm sorry - only the author of this article, @davannaw-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @shijojoy - Could you make this update in a pull request in the private repo? In that repo, you can sign off directly. Thanks! We'll close this pull request.

**Pull request closed without merging**
