### PR TITLE
updates for media references -5.

### PR DESCRIPTION
**Pull request by LouisBerner**

### CODE REVIEW

**Comment by LouisBerner** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman. Thanks.

**Comment by Jak-MS** [comment]
#assign: @ManikaDhiman 

@ManikaDhiman 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@LouisBerner - let me know if this is ready for review / merge by taking it out of draft mode and tagging me in a comment. Thanks.

**Comment by ManikaDhiman** [comment]
@Jak-MS: This PR is ready to merge. #sign-off

**Comment by LouisBerner** [comment]
@Jak-MS: This PR is ready to merge. #sign-off

**Comment by Jak-MS** [comment]
will merge. note that logos and diagrams generally shouldn't have a gray border (which is for screenshots).

**Pull request merged**
