### PR TITLE
Add elevation note to prereqs

### PR DESCRIPTION
**Pull request by erskinejohn**
Add elevation note to prereqs

### CODE REVIEW

**Comment by PRMerger9** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BryanLa** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
