### PR TITLE
Minor code fixes

### PR DESCRIPTION
**Pull request by BaileyLawson**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@BaileyLawson : Thanks for your contribution! The author, @mattbriggs, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Verified corrections to syntax.

**Comment by GitHubber17** [comment]
@BaileyLawson - Thank you for your contribution!

**Comment by cblackuk** [comment]
@GitHubber17 Thanks for merging! Making the world a better place! :-)

**Pull request merged**
