### PR TITLE
Improved readability and instructions for solution update monitoring - update-via-powershell-23h2.md

### PR DESCRIPTION
**Pull request by Karl-WE**
- seperated section for monitoring for better readabllity
- readability improvements for shell outputs
- added script to continuously monitor the update
- added information that Update progress can still be monitored via Azure Portal and how (different navigation approach as in "Azure Portal section"
- added check for UBR number which also confirms minor build number are similar across nodes

### CODE REVIEW

**Comment by Karl-WE** [comment]
Appreciate your review and corrections / formatting if any. Spent some time on this PR and how that the changes are helpful.

I propose the changes after updating 23H2 for the first time and had issues with the Azure Portal solution update deployment and so had to choose PowerShell route to complete.

**Comment by Jak-MS** [comment]
@alkohli 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Karl-WE** [comment]
To avoid merge issues due to the delay may I kindly ask if this is is reviewed @Jak-MS @Jak-MS

I would like to resolve the warning for you but the line specified in the message does not apply.

**Comment by Court72** [comment]
@alkohli

Can you review this PR? Sign off or approve if you accept the changes 

*Note*: To sign off, add a `#sign-off` comment to the PR.

**Comment by Karl-WE** [comment]
Dear @alkohli do you have time to review and sign-off?

**Comment by Karl-WE** [comment]
@alkohli have had time to check if this is ok to merge? Would definitely help the UX for update processes as long we have no integrated approach in the specific PowerShell command.

**Comment by alkohli** [comment]
@Karl-WE This PR is in review by the PM who owns this feature. As soon as I get the review back, I will create a private PR off this and proceed. Thank you for your patience while we get this done. And also thank you for your contribution!

**Comment by Karl-WE** [comment]
@alkohli is this still under review or outdated?

**Comment by Karl-WE** [comment]
@alkohli is this still in triage / review?

**Comment by alkohli** [comment]
#please-close

**Pull request closed without merging**
