### PR TITLE
Adding on-premises AD DC requirement

### PR DESCRIPTION
**Pull request by cpuck**
This is due to an issue a customer encountered in the forums.  https://docs.microsoft.com/en-us/answers/questions/547615/evaluating-34azure-stack-hci34-stuck-at-34join-a-d.html

### CODE REVIEW

**Comment by PRMerger16** [comment]
@cpuck : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by khdownie — COMMENTED** [review]
Would it be better to say: Create an Active Directory domain controller on-premises, if you don't already have one. The cluster will be unable to join Azure Active Directory Domain Services until it's registered with Azure.

**Comment by cpuck** [comment]
The cluster requires an on-premises AD domain controller.  This customer did not have one, but tried to join it to Azure Active Directory, but that will not work.  The registration piece is not dependent on AD nor AAD.  I'm trying to say, you need an on-prem AD no matter what and don't try to use AAD instead because that will not work at all.


Create an Active Directory domain controller on-premises, if you don't already have one. The cluster will be unable to join Azure Active Directory Domain Services until it's registered with Azure. (because it needs an on-premises Active Directory, despite being a hybrid solution).
Thanks,

Chris

**Comment by khdownie** [comment]
#sign-off

**Pull request merged**
