### PR TITLE
Update HW partner links

### PR DESCRIPTION
**Pull request by hectoralinares**
1 of 3

### CODE REVIEW

**Comment by PRMerger17** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
@hectoralinares Can you resolve your merge conflict. Thanks! Matt

**Comment by PRMerger18** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
@hectoralinares Thanks! #sign-off

**Comment by Jak-MS** [comment]
@hectoralinares - this PR is technically over the limit of what we are scoped to review in the public repository. I've reviewed and merged it this time, but as a Microsoft employee and program manager, you should be working in the private repositories. I've included some information below for how to get set up for that (in case you need it). The private repos have staging and validation tools that help us maintain the document repos meet the quality criteria. Can you use the private repos in the future? Thanks.

***
Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Pull request merged**
