### PR TITLE
fix image link to show the latest bigger image

### PR DESCRIPTION
**Pull request by cblackuk**
Currently it displays the smaller image and has got additional broken link:
image

Fixing to put the correct image and clean up the doc.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BryanLa** [comment]
@cblackuk - thanks very much for finding this and contributing! In this particular case, I'd like to pull your changes into our internal repo, so I can stage and test the changes. That link was also using the "lightbox" magnifier, which has slightly different syntax. I will make the changes and get this out in the next publishing slot, in about an hour from now. Thanks again!

#please-close

**Comment by cblackuk** [comment]
Thanks @BryanLa :-) I hope it will work internally and we can get it fixed :-)

**Comment by BryanLa** [comment]
@cblackuk - looks like it [published correctly now](https://docs.microsoft.com/azure-stack/operator/create-add-on-plan?view=azs-2005). Thanks again, for pointing this out.

**Comment by cblackuk** [comment]
Fantastic! Thank you so much! @BryanLa

**Pull request closed without merging**
