### PR TITLE
Update verbiage for upgrading from Server 2019

### PR DESCRIPTION
**Pull request by snickler**
This explanation makes it more clear to the readers that a rolling cluster upgrade is the current path to migrating from Server 2019 to Azure Stack HCI.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@snickler : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by khdownie** [comment]
@snickler please hold off - I'm working on another PR with changes to this same page. I'll roll this minor change in to avoid merge conflicts. You can delete this PR.

**Comment by khdownie** [comment]
I just merged another PR that includes this change. Should be live soon. Please delete this PR.

**Comment by ktoliver** [comment]
Closing the PR per author comments. Thanks.

**Pull request closed without merging**
