### PR TITLE
Update azure-stack-release-notes-known-issues-1906.md

### PR DESCRIPTION
**Pull request by kivenkat**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kivenkat** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@kivenkat: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Jak-MS** [comment]
@kivenkat - contributors in the public repo can't sign off on their own PRs. this PR will need to be approved or signed off by @sethmanheim ... or an exception made as described in an earlier comment.  Thanks.

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
