### PR TITLE
Update system-requirements.md

### PR DESCRIPTION
**Pull request by Elektronenvolt**
Document Firewall port requirements discussed in https://github.com/Azure/aks-hci/issues/97

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Elektronenvolt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by abhilashaagarwala** [comment]
@mattbriggs  - can you please approve this? @Elektronenvolt  - thank you so much for your contribution!

**Comment by mattbriggs** [comment]
@[Elektronenvolt](https://github.com/Elektronenvolt) Thanks!

#in-progress

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
