### PR TITLE
Update azure-arc-enabled-virtual-machines.md

### PR DESCRIPTION
**Pull request by BenoitNgs**
Add issue:
Appliance prepare command failed with error:  [Errno 13] Permission denied: 'debug_infra.yaml'

### CODE REVIEW

**Comment by PRMerger12** [comment]
@BenoitNgs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@BenoitNgs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ManikaDhiman** [comment]
@ZmanKyle: Could you please review this PR? Thanks!

**Comment by sethmanheim** [comment]
@ManikaDhiman I am pretty sure that images need to live in the docs repos, we cannot link to an image on GitHub.  

cc @ZmanKyle

**Comment by ManikaDhiman** [comment]
Thanks, @sethmanheim.

@ZmanKyle: Please let me know if the edits in this PR are required. If yes, I can create a separate PR to replicate these edits, resolve merge conflicts, and add images in the repo. Thanks!

**Comment by ZmanKyle** [comment]
@ManikaDhiman The changes here are valid, but we need to put this inside troubleshooting section.

**Comment by ManikaDhiman** [comment]
> @ManikaDhiman The changes here are valid, but we need to put this inside troubleshooting section.

Thanks for confirming, @ZmanKyle. I will work with you to include these changes in the troubleshooting section via a separate PR. Until then, let's keep this PR open for tracking purposes. Thanks!

**Comment by ManikaDhiman** [comment]
@BenoitNgs: Thanks for your contribution! This error description is now added to the troubleshooting article: https://learn.microsoft.com/en-us/azure-stack/hci/manage/troubleshoot-arc-enabled-vms

#please-close

**Pull request closed without merging**
