### PR TITLE
manual update setup

### PR DESCRIPTION
**Pull request by pipposera**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@pipposera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@Justinha: I'm sorry - only the author of this article, @PatAltimore, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger6** [comment]
@pipposera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
#sign-off

**Comment by tfosmark** [comment]
@pipposera @Justinha  Changes to articles must be done in the azure-stack-docs-pr repo (private) rather than the azure-stack-docs repo (public) so that we can have validated builds and verify content updates on staging. You should have permissions to azure-stack-docs-pr. Closing this pull request so that you can make updates in the private repo. Thank you.

**Comment by pipposera** [comment]
Tami,
This was completely unnecessary. I just saw this email and realized that the changed that I had submitted 2 weeks ago has not made it to the public documentation, resulting in customer escalations.

Filippo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request closed without merging**
