### PR TITLE
Adding caution note: As a deinstallation will also remove ARB created…

### PR DESCRIPTION
**Pull request by bfrankMS**
… VMs.

Thus could lead to loose productive workload. This is due to the current design.
We should warn the users about it - because there will be no prompt.

### CODE REVIEW

**Comment by bfrankMS** [comment]
#sign-off

**Comment by bfrankMS** [comment]
Hi Kilol,
work finished - if you are ok with it pls sign off ;-)
thx,
B

**Comment by ksurjan** [comment]
@Kyle ***@***.***> please take a look. Thanks.

-Kilol
________________________________

**Comment by Court72** [comment]
@ksurjan

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ZmanKyle** [comment]
#sign-off

**Comment by alkohli** [comment]
Added the PR for this change (reworded the note): https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/13001
The pR is merged, so signing this one off as well.

#sign-off

**Comment by Jak-MS** [comment]
@alkohli - the changes aren't the same here as in https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/13001.  Merging this will end up adding BOTH the CAUTION and the IMPORTANT. Do you still want to merge this?

**Comment by bfrankMS** [comment]
Hi Jak,

good catch. It was a long time ago - so changes were done from multiple ends regarding the same information.
----> IMHO only merge one of it.

Best
B

**Comment by Court72** [comment]
Closing this PR since the changes are already merged.

**Pull request closed without merging**
