### PR TITLE
Replaced  SMB Bandwidth Limit with FS-SMBBW

### PR DESCRIPTION
**Pull request by igomaa**
enable feature SMB Bandwith Limit generate an error when enable the feature , FS-SMBBW is the correct feature name (see below)

image

image

### CODE REVIEW

**Comment by Court72** [comment]
@ronmiab

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ronmiab** [comment]
@Court72 - verifying with the PM and will let you know what comes back.

**Comment by ronmiab** [comment]
#sign-off

**Review by ronmiab — APPROVED** [review]
per the PM, the SMB Bandwidth feature name is "FS-SMBBW". The article has the display name and that needs to be corrected. It should be the feature name as suggested in this PR.

**Comment by Jak-MS** [comment]
This was already added in main. Closing this.

**Pull request closed without merging**
