### PR TITLE
New page for running ASH disconnected and link to it from azure-stack-disconnected-deployment.md

### PR DESCRIPTION
**Pull request by GKAYED**
Details and nuances of running Azure Stack Hub in a fully disconnected environment that's hyperlinked from the azure-stack-disconnected-deployment.md page.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @GKAYED - Thanks for your pull request. A member of the content team will review it.

**Comment by ktoliver** [comment]
Hi @PatAltimore - Could you review the proposed new article? If it's approved, it will need to be moved to the private repo for automated validations, staging, and comprehensive PR review. Thanks.

(PRMerger assigned you automatically; should someone else be assigned for review?)

**Comment by PatAltimore** [comment]
Hi @GKAYED,

Thanks for the contribution. Unfortunately, I can't approve the submission as is. There are several issues dealing with metadata, links, style, and conventions that require fixing before this would meet the publishing criteria.

Most of this content exists in other articles. Did you find something that was missing? Or was it difficult to find the information?

Thanks,
Pat

**Comment by PRMerger13** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@GKAYED : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GKAYED** [comment]
@PatAltimore , Apologies changes didnt sync from VS Code. Can u pls double check. There should be updates now to styling, metadata, and all links should hopefully be updated. Let me know if there are still issues.

You're correct I thought it'll be helpful to have one article for all aspects of running ASH fully disconnected and combine all relevant information instead of finding info in so many places.

**Comment by PatAltimore** [comment]
Hi @GKAYED,

I'm going to request closing this PR. I sent you an internal email about it.

Thanks,
Pat

#please-close

**Comment by GKAYED** [comment]
Excellent. Thanks Pat

**Comment by PRMerger15** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.

**Pull request closed without merging**
