### PR TITLE
Update azure-stack-release-notes-known-issues-1906.md

### PR DESCRIPTION
**Pull request by efemmano**
added portal known issue as per icm 135399813

### CODE REVIEW

**Comment by PRMerger9** [comment]
@efemmano : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hectoralinares** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@hectoralinares: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by BryanLa** [comment]
Hi @MicrosoftDocs/apex-docs-pr-reviewers - we have an exception here, as @sethmanheim is OOF. I'm approving the PR for #sign-off in his absence. THanks!

**Comment by PRMerger7** [comment]
@BryanLa: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger13** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
