### PR TITLE
Update release-notes.md

### PR DESCRIPTION
**Pull request by rammalkani**
Edited the sections for pre-requisite hotfix for 2008 Update and moved the current for after the update.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@rammalkani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@rammalkani I don't see how this really clarifies things. If a customer is running 2005 and they read the 2008 release notes, they’ll see that all they need to do is upgrade to 2008 – they don’t need to install all the 2005 hotfixes first. If they’re running 2005 and they’re reading the 2005 release notes, they’ll see the section that says “if a hotfix is released for your build you should install it,” and there’s a link to the latest 2005 hotfix.

**Comment by rammalkani** [comment]
Here are two possibilities -
 Applied 2005 just now. He will get the latest fix installed along with the updates. Proceed to apply the 2008 update.

 Applied the initial release of 2005. No further update applied. For such scenarios, this statement provides clear information for the latest 2005 update to be applied. This information has been available for all previous updates for AzsH.

Ram.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sethmanheim** [comment]
@rammalkani OK, we can try your suggested edits, if that makes things clearer. Thank you for the feedback! #sign-off

**Review by sethmanheim — APPROVED** [review]

**Pull request merged**
