### PR TITLE
ASHCI OEM license

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by dansisson** [comment]
This is a draft version.

**Comment by Karl-WE** [comment]
for me, being into licensing, this was an interesting article though. Could have outlined that there are no Azure Hybrid Benefits for Azure Stack HCI when using OEM licenses, so usual costs of 10$ per active core applies

**Comment by alkohli** [comment]
Thank you for your feedback @Karl-WE! The official docs for these will be coming soon. Lalitha Ramesh is the product PM who owns this feature in case you have more questions.

**Comment by Karl-WE** [comment]
@alkohli I would be elated to connect with her. Could you send drop me a line off GitHub, please?

**Pull request closed without merging**
