### PR TITLE
Update azure-stack-vm-sizes.md

### PR DESCRIPTION
**Pull request by kentchen-msft**
the max data disks for DS_v2 series is incorrect.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@kentchen-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mattbriggs Could you take a look at this pull request from October?

Thanks.

**Comment by mattbriggs** [comment]
#in-progess

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
