### PR TITLE
Update Infra description

### PR DESCRIPTION
**Pull request by wamota**
Update the Infra description to avoid misunderstandings from customer on the requirements for this subnet, this is in response to issues related to an IcM.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@wamota : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
@wamota  some minor language changes.

**Comment by wamota** [comment]
> @wamota some minor language changes for your review.

Looks good to me, we need to publish this change.

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
