### PR TITLE
Migrate using PowerShell

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by Jak-MS** [comment]
@alkohli 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

NOTE: The commits will have to be moved to the private repo for a full review.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
Closing this PR. The content from this PR was pulled into this PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/15534

**Comment by alkohli** [comment]
#please-close

**Pull request closed without merging**
