### PR TITLE
instructions for removing extra Azure API permissions per customer request

### PR DESCRIPTION
**Pull request by scooley**
Added instructions for adding superfluous permissions when connecting WAC Azure for AKS-HCI.  I also did some linting.

/cc @abhilashaagarwala as FYI (and to add the right doc folks)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@scooley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @scooley - This pull request was created in the public repo. PMs are asked to work in the private repo. Could you submit this update in a new PR in the private repository, and then close this PR? Note that new images that are referenced in MD or YAML files must be added to a repository as image files; we can't reference images that are hosted elsewhere, per the repo admins. 

Thanks. #hold-off

**Comment by scooley** [comment]
Closing - moved to private repo

**Comment by ktoliver** [comment]
Thanks @scooley.

**Pull request closed without merging**
