### PR TITLE
Update azure-stack-vpn-gateway-settings.md

### PR DESCRIPTION
**Pull request by CarlosGon**
| | Tunnel throughput |VPN gateway maximum IPsec tunnels |

### CODE REVIEW

**Comment by PRMerger15** [comment]
@CarlosGon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@CarlosGon Thank you for the input, can you please explain further the change you are proposing?

**Comment by sethmanheim** [comment]
#in-progress

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
