### PR TITLE
typo: depploymentdata -> deploymentdata

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@rjagiewich : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
verified editorial correction

**Comment by sethmanheim** [comment]
@nschonni Thank you for catching this! We can definitely merge the fix, although it appears possibly there is a merge conflict? 
#sign-off

**Comment by nschonni** [comment]
It's not a merge conflict, but someone has turned on "Require branches to be up to date before merging" in this repo. https://help.github.com/en/articles/types-of-required-status-checks

**Comment by BryanLa** [comment]
@sethmanheim , @nschonni - yes, not sure who turned that on, but I just turned it off again.

**Pull request merged**
