### PR TITLE
Update azure-stack-prepare-pki-certs.md

### PR DESCRIPTION
**Pull request by erskinejohn**
Adding ConvertTo-AzsPFX steps. This function automates the original manual steps of this page and includes the validation steps on the next page.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@mattbriggs: I'm sorry - only the author of this article, @IngridAtMicrosoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@johnerskine I'll go ahead and merge this PR here (in the public repo) because it's approved. Thanks.

**Comment by mattbriggs** [comment]
@ktoliver I'll be working on some of @IngridAtMicrosoft for a bit. Do you need me to send a note to techdocprs? Thanks, Matt

**Pull request merged**
