### PR TITLE
Formatting and link adding

### PR DESCRIPTION
**Pull request by jameswylde**
General PS code formatting + adding PEP documentation hyperlink in first mentioned instance of it (as PEP is only mentioned in abbreviated form in entire doc)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jameswylde : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@BryanLa 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
Hi @Jak-MS , @jameswylde  - Thanks very much for this contribution.

I'd like to propose that we close this PR, and pull James' branch into an internal repo PR. There are some proposed changes that need to be updated, and I'd like to be able to verify them with our internal staging environment. I will cc: @jameswylde on it as well so he can track/comment accordingly. Please let me know..

**Comment by jameswylde** [comment]
Sure @BryanLa as this was only a formatting PR, happy to go with your suggestion - please cc me or let me know if anything else is needed internally from the AzSH team.

**Pull request closed without merging**
