### PR TITLE
[DO NOT MERGE to master] : Update docs to reflect single combined test run for OEM workflow

### PR DESCRIPTION
**Pull request by ankoshe1**
Hi Matt,
We have a feature that we will release next week. We would like the documentation to go public along with that release (not earlier).
However I am getting my PR ready and reviewed by you and my teammates so it will be ready to merge when we are spinning off the release.

Thank-you!

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ankoshe1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@ankoshe1 - are you a Microsoft employee? If so, you should link your GitHub account with your MS account and be working in the private repository.

tagging @mattbriggs for visibility

here's some information about working in the private repos:
> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  
> 
> After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  
> 
> If you need help getting set up to work in the private repo, see [How to get to the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master#how-to-get-to-the-private-repo). You can also take a look at the [GitHub account setup page](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master) for additional details on making sure you're set up.

**Comment by ankoshe1** [comment]
Hi,
I had to create a new github account and the new one was not linked to my Microsoft account.
I just unlinked my old github account (ankoshe) and linked the new one (ankoshe1).

Thanks!
Anagha.

**Comment by GitHubber17** [comment]
Hi @ankoshe1 - Thank you for updating your accounts. As the previous reviewer mentioned, Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. We'll close this PR. Thank you.
Cc @mattbriggs

**Pull request closed without merging**
