### PR TITLE
Storage Account media folder rename

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by Jak-MS** [comment]
@dansisson - when this is ready for review, can you take it out of draft mode and tag @ManikaDhiman and @alkohli in a comment? thanks!


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@ManikaDhiman @dansisson - merging this. A couple requests:

1. please make sure to check the live page after the changes are published to confirm that the images are displaying as intended. 
2. the screenshot : `/media/virtual-machine-image-storage-account/deployment-in-progress.png` displays a "Correlation ID" - is that private information? Should it be obscured?

   image

thanks

**Pull request merged**
