### PR TITLE
Marketplace differences based on Cloud environment

### PR DESCRIPTION
**Pull request by CHDAFNI-MSFT**
Replicating a Note from the 'Download Marketplace items to Azure Stack Hub' page as it relates to marketplace differences

### CODE REVIEW

**Comment by PRMerger17** [comment]
@CHDAFNI-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cblackuk — CHANGES_REQUESTED** [review]
I think it would read better if it was:
"(...) based on the cloud environment your Azure Stack Hub system is connected to (...)"
Missing the environment bit.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by sethmanheim** [comment]
@cblackuk I added this, thank you for the suggestion.

**Pull request merged**
