### PR TITLE
Update uninstall instructions to include powershell core locations

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@bganapa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
