### PR TITLE
Update powershell-install-az-module.md

### PR DESCRIPTION
**Pull request by CarlosGon**
to be consistent with connected method:
Install-Module -Name AzureStack -RequiredVersion 2.0.2-preview -AllowPrerelease

Disconnected
Save-Package -ProviderName NuGet -Source https://www.powershellgallery.com/api/v2 -Name AzureStack -Path $savedModulesPath -Force -RequiredVersion 2.0.2-preview

### CODE REVIEW

**Comment by PRMerger16** [comment]
@CarlosGon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cblackuk — APPROVED** [review]
LGTM

**Comment by ktoliver** [comment]
@cblackuk - Thanks for your review! In the public repo, the author or another member of the content team, or a PM for the service, needs to approve the PR before it can be merged. Thanks.

@mattbriggs - Could you review the proposed change to your article? Thanks.

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
@cblackuk Thanks! #sign-off

**Comment by cblackuk** [comment]
Thank you @mattbriggs!

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
