### PR TITLE
Update nested-resiliency md - Update supported OS Versions

### PR DESCRIPTION
**Pull request by Karl-WE**
To minimize the efforts I have made the requirements future proof. No sense to update every year for Azure Stack HCI and Windows Server releases.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@JasonGerend 
Can you review the proposed changes? 

Note the 'author' value seems to be incorrect or inconsistent. Can you update that as well? thanks 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Karl-WE** [comment]
Any updates on this?

**Comment by alkohli** [comment]
@Karl-WE Looking at this. Given both 20H2 and 21H2 are out of service, I will say Azure Stack HCI, version 22H2 and newer. And pick these changes from your PR and open a new PR. #in-progress

**Comment by alkohli** [comment]
@Karl-We Here is the new PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/16439. Will be closing this PR.

**Comment by alkohli** [comment]
#please-close

**Comment by Karl-WE** [comment]
> @Karl-We Here is the new PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/16439. Will be closing this PR.

Cannot open the link private repo? @alkohli

**Pull request closed without merging**
