### PR TITLE
Update update-akshci-host-powershell.md

### PR DESCRIPTION
**Pull request by Elektronenvolt**
adding -AcceptLicense to avoid this error msg:
PackageManagement\Install-Package : License Acceptance is required for module 'DownloadSdk'. Please specify '-AcceptLicense' to perform this
operation.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Elektronenvolt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mkostersitz for review

Thanks.

**Review by oilcan-productions — APPROVED** [review]
LGTM

**Comment by ktoliver** [comment]
Verified approval; merging. Thanks, all.

**Pull request merged**
