### PR TITLE
Update aks-edge-howto-setup-nested-environment.md

### PR DESCRIPTION
**Pull request by dmc-tech**
Fix command to assign IP address to Nat vSwitch. Previous version assigned an incorrect IP and default gateway, in effect, not creating the gateway.

### CODE REVIEW

**Comment by Court72** [comment]
@fcabrera23

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by fcabrera23 — APPROVED** [review]
LGTM

**Comment by fcabrera23** [comment]
#sign-off

**Comment by Jak-MS** [comment]
merging now

**Pull request merged**
