### PR TITLE
From private repo

### PR DESCRIPTION
**Pull request by huypub**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@huypub : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@PRMerger7 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@huypub - Per the PR quality criteria in the [internal contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master#extraneous), the two DS_Store files that are in the pull request should be removed from the pull request; they aren't allowed in the repository, and they might be causing the build issue you're seeing.

image

It looks like they were added by @mattbriggs (for informational purposes).

**Comment by PRMerger12** [comment]
@v-albemi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@BryanLa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@sethmanheim : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@BryanLa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
