### PR TITLE
Resiliency reserve and available memory for VMs clarification

### PR DESCRIPTION
**Pull request by ecaha**
I was confused about how to calculate available memory for tenant workload VMs placing, so I tried to clarify it.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@ecaha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PatAltimore** [comment]
#assign: @BryanLa

**Comment by BryanLa** [comment]
@ecaha - thanks very much for your proposal. We're looking into this and will get back to you as soon as we can review.. 

cc: @troettinger

**Pull request merged**
