### PR TITLE
Fix erratum

### PR DESCRIPTION
**Pull request by jirenugo**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@jirenugo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jirenugo** [comment]
@v-susbo , can you take a look at this?

**Comment by ktoliver** [comment]
@v-susbo for review

Thanks.

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@mattbriggs: I'm sorry - only the author of this article, @v-susbo, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
