### PR TITLE
fix-1904-known-issues-broken-link

### PR DESCRIPTION
**Pull request by cblackuk**
I made a mistake when I did https://github.com/MicrosoftDocs/azure-stack-docs/pull/119 - this PR is to fix it.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@cblackuk : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Already fixed upon my review. #please-close

**Comment by cblackuk** [comment]
@sethmanheim so where is that review as the link is currently broken?

**Comment by sethmanheim** [comment]
@cblackuk Sorry about that -- your PR was inadvertently merged before I could review it, so I went back and made the fixes (fixed some language as well). It should be live after 3 PM PDT.

**Comment by cblackuk** [comment]
@sethmanheim oh ok :-) cool, for as long as we get it fixed I am good. Thanks a lot for looking into it! Really appreciate the help!

**Pull request closed without merging**
