### PR TITLE
Update Validate Azure Stack Certificates syntax

### PR DESCRIPTION
**Pull request by erskinejohn**
Update Validate Azure Stack Certificates syntax and certificate types.
Note: The link to PaaS cert validation on https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-1910 will be invalid after this change.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by Jak-MS** [comment]
hi @erskinejohn - due to the number of changes in this PR, we need to move the commits to the private repository so we can take advantage of proofing, validation, and staging tools there. 

@mattbriggs - we'll assign the new PR to you for a quick review and sign off when it's ready.

Thanks.

**Comment by Jak-MS** [comment]
New PR https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/2086

**Comment by erskinejohn** [comment]
The URL doesn’t seem valid.

**Comment by Jak-MS** [comment]
Hi @erskinejohn - the link appears to give a 404 because you don't have access to the private repo. Once we've checked the changes for any issues, they'll be merged into the master branch and published live where you'll be able to see them. The PR is still in process at this time. thanks.

**Pull request merged**
