### PR TITLE
updates for media references in manage -3.

### PR DESCRIPTION
**Pull request by LouisBerner**

### CODE REVIEW

**Comment by LouisBerner** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman. Thanks.

**Comment by Jak-MS** [comment]
@ManikaDhiman 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ronmiab — COMMENTED** [review]
@LouisBerner - the updates look good to me. Only one questionable is whether you should remove the subscription id or create some "dummy" info for azure-stack/hci/manage/media/manage-cluster-registration/3-get-azurestackhci.png.

I know it's partially cut off, but not by much. Also, if there is any concern about the serial numbers on image azure-stack/hci/manage/media/manage-cluster-registration/cluster-status-2.png, that can be adjusted to.

Let's see if Manika has any additional insight.

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@LouisBerner - just a couple issues that need to be addressed before we can merge this PR.

1. media/manage-cluster-registration/cluster-status-1.png - the blue block that is used to obscure personal information needs to be the same color as the background blue. Can you address this?

   image

1. /media/manage-cluster-registration/cluster-status-2.png - same issue. the blue block should be the same color as the background blue. Additionally, the subscription ID is only partially obscured ... and it should be fully masked.

   image

Go ahead and sign off and tag me when you've addressed these issues and I'll take a look again. 

fyi @ManikaDhiman 
#hold-off

**Comment by LouisBerner** [comment]
@alkohli 
@ManikaDhiman
@ronmiab
@Jak-MS 

Updated artwork files in this PR iteration:

 - azure-stack/hci/manage/media/manage-cluster-registration/3-get-azurestackhci.png.
 - azure-stack/hci/manage/media/manage-cluster-registration/cluster-status-1.png.
 - azure-stack/hci/manage/media/manage-cluster-registration/cluster-status-2.png.

Thank you!

#signoff - Ready to merge and go live. Thx.

**Comment by Jak-MS** [comment]
@LouisBerner - looks great. thanks!

**Pull request merged**
