### PR TITLE
Sentense need to be fixed

### PR DESCRIPTION
**Pull request by kojinak**
Sentense ends halfway.    "In addition to running VMs, memory is consumed by any VMs that have landed on the fabric. This means that VMs that are in "Creating", "Failed" or VMs shut down from within the g"

### CODE REVIEW

**Comment by PRMerger13** [comment]
@kojinak : Thanks for your contribution! The author(s) have been notified to review your proposed change. @prchint

**Comment by Jak-MS** [comment]
@prchint-zz - can you update the ms.author metadata value when you address this PR? Thanks.

**Comment by sethmanheim** [comment]
@prchint Hey Theebs, since you're the listed author of the article, can you resolve the merge conflict and sign off on this one? Thanks!

**Comment by jborsecnik** [comment]
@prchint-zz, can you review these changes? Also see https://github.com/MicrosoftDocs/azure-stack-docs/pull/285#issuecomment-517842336. Thanks.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved the merge conflict, which completes the sentence. Merging the PR.

**Pull request merged**
