### PR TITLE
Update CSR generation with new syntax

### PR DESCRIPTION
**Pull request by erskinejohn**
Update CSR generation with new syntax and certificate types.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
#sign-off

**Comment by kongou-ae** [comment]
Hello @Justinha and @erskinejohn ,

I tried the new way and encountered an error. `-certificateType EventHub` raised the following error. I guess that this option should be `-certificateType EventHubs`. Or the ValidateSet in Microsoft.AzureStack.ReadinessChecker should be fixed from EventHubs to EventHub.

Sorry for my Japanese error message.
```
PS C:\WINDOWS\system32> New-AzsCertificateSigningRequest -certificateType EventHub -RegionName $regionName -FQDN $externalFQDN -subject $subject -OutputRequestPath $OutputDirectory
New-AzsCertificateSigningRequest : パラメーター 'CertificateType の引数を確認できません。引数 "EventHub" は、ValidateSet 属性で指定されたセット "EventHubs,IoTHub,DBAdapter,AppServices,Deployment,DataboxEdge" に属していま
せん。このセットの引数を指定して、コマンドを再度実行してください。
発生場所 行:1 文字:51
+ New-AzsCertificateSigningRequest -certificateType EventHub -RegionNam ...
+                                                   ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzsCertificateSigningRequest]、ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-AzsCertificateSigningRequest
```

Best regards.

**Comment by ShannonLeavitt** [comment]
Hi @Justinha 

Could you review the message from @kongou-ae ? If you're okay to continue with the merge, go ahead and sign off again.

Thanks!

#hold-off

**Comment by erskinejohn** [comment]
@justinha this change is required, the example should be -CertificateType EventHubs with an “s”
Apologies for the confusion.
John

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
