### PR TITLE
updated the syntax to reflect the support 32-bit ASN with a border de…

### PR DESCRIPTION
**Pull request by ebmarquez**
updated document to show support for 32-bit ASN at a customer border device.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ebmarquez : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ebmarquez** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ebmarquez: I'm sorry - only the author of this article, @IngridAtMicrosoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by IngridAtMicrosoft** [comment]
in-review

**Comment by IngridAtMicrosoft** [comment]
#sign-off

Thanks Eric!

**Pull request merged**
