### PR TITLE
Add note to re-enable multitenancy postupdate

### PR DESCRIPTION
**Pull request by PPacentMSFT**
Add note to re-enable multitenancy post-update

### CODE REVIEW

**Comment by PRMerger6** [comment]
@PPacentMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PPacentMSFT** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@PPacentMSFT: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by BryanLa** [comment]
#sign-off on behalf of @sethmanheim

**Comment by PRMerger19** [comment]
@BryanLa: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger9** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
