### PR TITLE
Update to add Container Registry to TOC

### PR DESCRIPTION
**Pull request by chasat-ms**
Please review TOC entries for Container Registry

### CODE REVIEW

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
@chasat-ms Thanks!

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@mattbriggs: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@mattbriggs: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mattbriggs** [comment]
@sethmanheim Not sure who the author is in the metadata for the TOC. Can you sign off? Thanks! Matt

**Comment by mattbriggs** [comment]
#please-close

**Pull request closed without merging**
