### PR TITLE
Security updates for 23h2 - port from WS

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @alkohli. Thanks.

**Comment by dansisson** [comment]
This is a draft version.

**Comment by Jak-MS** [comment]
@alkohli @ManikaDhiman 
- Can you review this PR when it's ready?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

#assign: @ManikaDhiman 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
@dansisson pulled the changes into a private PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/14690
You can close this PR now.

**Pull request merged**
