### PR TITLE
Update azure-stack-node-actions.md

### PR DESCRIPTION
**Pull request by prchint**
updated typo

### CODE REVIEW

**Comment by PRMerger6** [comment]
@prchint : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by prchint** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@prchint: I'm sorry - only the author of this article, @mattbriggs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
