### PR TITLE
Updated networking issues

### PR DESCRIPTION
**Pull request by ScottNapolitan**
Issues have been reported in 1902

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ScottNapolitan : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by ScottNapolitan** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ScottNapolitan: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@Jak-MS : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Pull request merged**
