### PR TITLE
Update create-cluster-powershell.md

### PR DESCRIPTION
**Pull request by InsideTechnologiesSrl**
Fix row 217 where the cmdlet was not correct

### CODE REVIEW

**Comment by PRMerger8** [comment]
@InsideTechnologiesSrl : Thanks for your contribution! The author(s) have been notified to review your proposed change. @v-dasis

**Comment by Court72** [comment]
@tmmarshall

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by InsideTechnologiesSrl** [comment]
What you mean? The cmdlet was wrong....you cannot create a variable and then run a command in the same line....check after and before to see the difference.

Ufficio Tecnico


[cid:logo-duerighe-orizzontale_fd9952ef-7c01-4f9f-bc02-0cff2cac8ab9.png]

p: +39 02.30456268?
e: ***@***.***
w: www.insidetechnologies.it

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by PRMerger6** [comment]
@InsideTechnologiesSrl: I'm sorry - only the author of this article, @v-dasis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
@JasonGerend - Would you be able to review this PR?

**Comment by InsideTechnologiesSrl** [comment]
Hi Shannon,

there's nothing too much to add...as I wrote, in this page: Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI | Microsoft Docs<https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell>

there's an error inside the script

***@***.***

The right one is

$ClusterName="cluster1"
New-Cluster -Name $ClusterName -Node $ServerList -nostorage

That's it...

Cheers
S

Ufficio Tecnico


[cid:logo-duerighe-orizzontale_fd9952ef-7c01-4f9f-bc02-0cff2cac8ab9.png]

p: +39 02.30456268?
e: ***@***.***
w: www.insidetechnologies.it

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by sethmanheim** [comment]
Fixed in the private repo. #please-close

**Pull request closed without merging**
