### PR TITLE
Azure Developer support plan for Azure Stack HCI

### PR DESCRIPTION
**Pull request by tayasuta**
We can get Azure Azure Stack HCI support with Azure Developer support plan.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@tayasuta : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by tayasuta** [comment]
@Jak-MS   Can I ask the current status of this request, please ?

**Comment by Jak-MS** [comment]
@JohnCobb1 - can you take a look at the changes in this PR?  If they look good, you can add `#sign-off` in a comment. Thanks.

@ktoliver , fyi

**Review by JohnCobb1 — CHANGES_REQUESTED** [review]
Hi @Jak-MS Suggest changing the update to read : "To create an Azure Stack HCI support request requires one of the following Azure support plans: Standard, Professional Direct, or Developer. You cannot use the Basic plan."

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
> Hi @Jak-MS Suggest changing the update to read : "To create an Azure Stack HCI support request requires one of the following Azure support plans: Standard, Professional Direct, or Developer. You cannot use the Basic plan."

@JohnCobb1 and @tayasuta - We've revised the original update and will merge the PR now. Thanks, all.

**Pull request merged**
