### PR TITLE
(Azure CXP) https://github.com/MicrosoftDocs/azure-stack-docs/issues/…

### PR DESCRIPTION
**Pull request by SumanthMarigowda-MSFT**
…1219

### CODE REVIEW

**Comment by PRMerger19** [comment]
@SumanthMarigowda-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SumanthMarigowda-MSFT** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@SumanthMarigowda-MSFT: I'm sorry - only the author of this article, @PatAltimore, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@PatAltimore - Could you review the proposed change to your article? If it's approved, I can change the URL to a relative link (and remove the locale in the URL) before merging. Thanks.

**Comment by PatAltimore** [comment]
Hi @SumanthMarigowda-MSFT and @ktoliver,

I fixed the link yesterday in the private repo. Alex opened the issue https://github.com/MicrosoftDocs/azure-stack-docs/issues/1219. The change should sync and publish today. I'm going to close this PR to avoid conflicts.

Thanks,
Pat
#please-close

**Comment by ktoliver** [comment]
Thanks @PatAltimore

**Pull request closed without merging**
