### PR TITLE
Update azure-stack-updates.md

### PR DESCRIPTION
**Pull request by justinincarnato**
Added brief section on Full v Express. 
Formatting

### CODE REVIEW

**Comment by PRMerger6** [comment]
@justinincarnato : Thanks for your contribution! The author, @mattbriggs, has been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@Jak-MS : Thanks for your contribution! The author, @mattbriggs, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @justinincarnato - can you submit content updates through the private repository in the future? I've provided some information below.

Also, the Azure Stack administration portal does not seem to be a branded product name and should not be capitalized. I've modified that part of your PR. Thanks.

***
Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master). 

Thanks.

**Pull request merged**
