### PR TITLE
DC Firewall WAC media folder rename

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by Jak-MS** [comment]
#assign: @ManikaDhiman

@alkohli @ManikaDhiman 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by ManikaDhiman** [comment]
@Jak-MS: Could you please review this PR? I had signed it off last week. Please let me know if there is anything else I need to do. Thanks!

**Comment by Jak-MS** [comment]
@ManikaDhiman - thanks for tagging me again. Not sure how this one slipped past.

@dansisson - merging this. with the :::image::: syntax, there's not way for us to see if there are any broken calls due to typos, so can you make sure to check the live page after the changes are published to confirm that the images are displaying as intended? 

thanks

**Pull request merged**
