### PR TITLE
Updated the document to reflect the WAC changes

### PR DESCRIPTION
**Pull request by shijojoy**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@shijojoy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shijojoy** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@shijojoy: I'm sorry - only the author of this article, @IngridAtMicrosoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @shijojoy - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Pull request closed without merging**
