### PR TITLE
Update azure-stack-capacity-planning-compute.md

### PR DESCRIPTION
**Pull request by kivenkat**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@kivenkat : Thanks for your contribution! The author, @prchint, has been notified to review your proposed change.

**Comment by kivenkat** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@kivenkat: I'm sorry - only the author of this article, @prchint, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by prchint** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
