### PR TITLE
Update prep instructions - customer feedback

### PR DESCRIPTION
**Pull request by hectoralinares**
- folder structure - timestamp/backupid
- cert folder name

### CODE REVIEW

**Comment by PRMerger7** [comment]
@hectoralinares : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
