### PR TITLE
Remove AzS-BGPNAT01

### PR DESCRIPTION
**Pull request by kojinak**
Currently ASDK doesn't need BGPNAT.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@kojinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@kojinak Can you please lowercase "host," as in "ASDK host". Otherwise looks good, thank you for the contribution! Please make that change and we will sign off.

**Comment by PRMerger12** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
