### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by abhilashaagarwala**

### CODE REVIEW

**Comment by abhilashaagarwala** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@abhilashaagarwala: I'm sorry - only the author of this article, @davannaw-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by davannaw-msft — APPROVED** [review]

**Comment by abhilashaagarwala** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@abhilashaagarwala: I'm sorry - only the author of this article, @davannaw-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @abhilashaagarwala - This pull request was opened in the public repo. Would you make future updates in the private repo? Thanks!

**Comment by abhilashaagarwala** [comment]
Hi @ktoliver sure! This needed to go live ASAP, but next time I will follow due process. Do you know when can I expect this change in the public docs?

**Comment by ktoliver** [comment]
Possibly 3 PM, if it was pulled into the build for publishing. If not, it won't publish until Sunday.

Working in the public repo is not faster; it requires an additional step of being synced with the private repository, and you have access to auto-merging in the private repo. 👍🏻

**Comment by ktoliver** [comment]
Possibly ~3 PM, if the update was pulled into the build for publishing.

**Comment by abhilashaagarwala** [comment]
Is it possible to get a publish before Sunday? Curious about what the process would look like..

**Comment by ktoliver** [comment]
I'll send you an email.

**Pull request merged**
