### PR TITLE
Update Registration Validation with 2011

### PR DESCRIPTION
**Pull request by erskinejohn**
With the release of Azure Stack 2011, we will update ReadinessChecker to depend on Az.Accounts (rather than AzureRM)
AzureRM users should specify Install-Module Microsoft.AzureStack.ReadinessChecker -requiredversion 1.2100.1396.426.
Az users should just install the tool normal Install-Module Microsoft.AzureStack.ReadinessChecker

This change should go at the same time as Azure Stack 2011 release.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @IngridAtMicrosoft - The pull request needs to be assigned to someone to work on. PRMerger automatically assigns it to the author that's listed in the article metadata. If you're not the right person to review the pull request, could you let us know who would be better able to review it? Thanks.

**Comment by erskinejohn** [comment]
@Bryan Lamos<mailto:bryanla@microsoft.com>, IIRC this PR (my original one) can be abandoned given you kindly staged them in the 2011 branch already?

**Comment by BryanLa** [comment]
Hi @erskinejohn - that was actually for [PR 1192](https://github.com/MicrosoftDocs/azure-stack-docs/pull/1192/files), which was your changes to the Validate Identity article. I ported these changes to the release-2011 branch, in the private repo ([PR 6140](https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/6140).

If you're OK with these ones going into 'master', once @IngridAtMicrosoft signs off they will eventually flow into release-2011 as well. Otherwise, the same would need to be done for this PR 1193 (ie: close, reopen a new PR in the private repo that targets release-2011).

HTH!

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@IngridAtMicrosoft @PatAltimore @BryanLa Thoughts on whether these changes (submitted Dec 2020) should be merged in or the PR closed?

Thanks.

**Comment by BryanLa** [comment]
@ktoliver  - I believe since 2011 release almost a year ago, these can problem just be merged into 'master' now.
@erskinejohn  - Can you confirm?

**Review by PatAltimore — APPROVED** [review]

**Comment by PatAltimore** [comment]
Hi @ktoliver,

This is okay to merge. #sign-off

Pat

**Pull request merged**
