### PR TITLE
Add alternative instruction and link to verify OAW.zip hash

### PR DESCRIPTION
**Pull request by yil578**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@yil578 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattbriggs — APPROVED** [review]
Sending you some feedback on teams

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
