### PR TITLE
Change to apiserver from master-FQDN

### PR DESCRIPTION
**Pull request by kojinak**
master-FQDN has been deprecated

### CODE REVIEW

**Comment by PRMerger17** [comment]
@kojinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mattbriggs Could you review this proposed update to your article?

Thank you!

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by ktoliver** [comment]
Thanks @mattbriggs

**Pull request merged**
