### PR TITLE
updates for media references in manage -1.

### PR DESCRIPTION
**Pull request by LouisBerner**

### CODE REVIEW

**Comment by LouisBerner** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman. Thanks.

**Comment by Jak-MS** [comment]
@ManikaDhiman 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
@Jak-MS: This PR is ready to merge. #sign-off

**Comment by Jak-MS** [comment]
@LouisBerner @ManikaDhiman - this looks good, merging.  however, without staging, we can't check the lightbox links (unsure if validation will catch any errors in those in the public repo). In any case, could you follow-up after this goes live to check all that the lightbox is working on all these images? thanks.

**Pull request merged**
