### PR TITLE
Update ADFS Windows Version

### PR DESCRIPTION
**Pull request by jbpaux**
Azure Stack Hub uses Windows Server 2019 since 1908 release

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jbpaux : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BryanLa** [comment]
@jbpaux - thanks very much for your contribution. I believe this is referring to the Windows OS version, when a customer uses an existing AD FS server from their own environment. Let me verify with the engineering team before proceeding and I will get right back to you..

**Comment by jbpaux** [comment]
@BryanLa The line just below the one I've amended is about customer ADFS environment. This one is about stamp builtin ADFS.

**Comment by BryanLa** [comment]
@jbpaux - yes, my apologies. I realized that later and forgot to come back and update my comment. I'm still discussing this change w/them. I'll post another update soon.

**Comment by BryanLa** [comment]
@jbpaux  - the consensus is to remove the version number of the first/internal bullet. We're also going to make slight change to the sentence preceding the bullets. Please let know if you'd like to do the former by pushing another commit to this PR, and I can follow up with another PR to do the latter. Or if you'd like close this one and I can just do both in a separate PR. And thanks again for this contribution.

**Comment by jbpaux** [comment]
Ok. I'll let you do both, it makes more sense. And I agree it's better to hide version number as we're not supposed to know azure stack internals

**Pull request closed without merging**
