### PR TITLE
Update hci-recommended-urls-table.md

### PR DESCRIPTION
**Pull request by RodriCoto**
Unable to retrieve Windows Updates. In the WindowsUpdate.log we saw that node could not communicate with end point: 'https://fe3cr.delivery.mp.microsoft.com/ClientWebService/client.asmx'

Maybe doc could be updated from:
| Microsoft Update | dl.delivery.mp.microsoft.com    | 443  | For Microsoft Update, which allows the OS to receive updates.  |
To:
| Microsoft Update | *.delivery.mp.microsoft.com    | 443  | For Microsoft Update, which allows the OS to receive updates.  |

Log snippet:
2023/01/10 14:14:31.9388814 14216 9796  WebServices     WS error: There was an error communicating with the endpoint at 'https://fe3cr.delivery.mp.microsoft.com/ClientWebService/client.asmx'.
2023/01/10 14:14:31.9388826 14216 9796  WebServices     WS error: The given proxy cannot be reached.

Thanks!

### CODE REVIEW

**Comment by Court72** [comment]
@ManikaDhiman 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
@tiaramathur: Could you please review these changes and let me know if they are good to be merged?

**Comment by danielleemsft** [comment]
@ManikaDhiman - looking at this doc, there are actually two changes required:
 - in "Recommended firewall URLs" section, update the following row to include both 80 and 443 ports
    Microsoft Update / dl.delivery.mp.microsoft.com / 443
 - in the same section, add the following as a new row
    Microsoft Update / *.delivery.mp.microsoft.com / 80, 443 / For Microsoft Update, which allows the OS to receive updates.

**Comment by ManikaDhiman** [comment]
Hi @danielleemsft, @RodriCoto: The Recommended firewall URLs section is now updated to include the new/updated URL info: [Recommended firewall URLs](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements#recommended-firewall-urls).

The changes are already merged and published via a private repo PR; hence closing this PR. Thanks!

#please-close

**Pull request closed without merging**
