### PR TITLE
Adding aka.ms for automatic update redirection

### PR DESCRIPTION
**Pull request by PPacentMSFT**
Adding aka.ms for automatic update redirection at https://aka.ms/azurestackautomaticupdate

### CODE REVIEW

**Comment by PRMerger13** [comment]
@PPacentMSFT : Thanks for your contribution! The author, @jeffgilb, has been notified to review your proposed change.

**Comment by jeffgilb** [comment]
#sign-off

**Comment by jeffgilb** [comment]
#sign-off

**Comment by jeffgilb** [comment]
Hi @ktoliver this one doesn't seem to be merging for some reason?

**Comment by NeilBird** [comment]
@ktoliver - This has still not been merged yet? - I have a customer chasing me on this PR, as they IT Security process requires that the documentation shows the URLs before they update the rules on their firewall / proxies. Thanks

**Pull request merged**
