### PR TITLE
[doc] [release notes] Added reference to AKS engine release on Azure Stack

### PR DESCRIPTION
**Pull request by walterov**
In the "What's new" section of the release notes for 1910 added reference to AKS engine release on Azure Stack

### CODE REVIEW

**Comment by PRMerger6** [comment]
@walterov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@walterov Please remove the /en-us locale specifier from the link target.

**Comment by PRMerger10** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@sethmanheim, I removed the "en-us" from the URL. Can you sign off on this PR, or does it have to go to someone else? Thanks.

**Comment by sethmanheim** [comment]
@jborsecnik I would ideally like this internal user to use the private repo, but I guess that's not going to happen, so -- #sign-off

**Comment by walterov** [comment]
Thanks @Seth Manheim<mailto:sethm@microsoft.com>, I was about to use the repo you referenced when I saw the signoff email thread. I’ll keep it in mind for any other PRs.

Thanks a lot!

Walter.

**Comment by PRMerger20** [comment]
@walterov: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jborsecnik** [comment]
@sethmanheim, thanks.

@walterov, info about Microsoft employees working the private repos is available at [Should I work in a private or a public repo?](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master)

**Comment by PRMerger7** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@sethmanheim, we can't use "ARM" (line 96). Ok to use "Azure Resource Manager" instead?

**Comment by sethmanheim** [comment]
No worries, I think we're good now. #sign-off

**Comment by sethmanheim** [comment]
> @sethmanheim, we can't use "ARM" (line 96). Ok to use "Azure Resource Manager" instead?

@jborsecnik Yes, that's fine, thanks for catching that!

**Comment by PRMerger20** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
