### PR TITLE
Update azure-stack-vaas-release-notes.md

### PR DESCRIPTION
**Pull request by ankoshe1**
Update release notes for release 4.4.6.35

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ankoshe1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
