### PR TITLE
Adding known issue for preparation prerequisite failures

### PR DESCRIPTION
**Pull request by PPacentMSFT**
Adding known issue for preparation prerequisite failures

### CODE REVIEW

**Comment by PRMerger19** [comment]
@PPacentMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Looks good, thank you: #sign-off

**Comment by PRMerger19** [comment]
@chbain : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chbain** [comment]
Minor style edit: Removed quotes from new content.

**Pull request merged**
