### PR TITLE
Point to the right SUSE BYOS images instead to the PAYG images; fixed…

### PR DESCRIPTION
**Pull request by petersatsuse**
… version

fixed wrong link to BYOS images instead of PAYG images and remove cut'n'paste error "SP3" from the SLES 15, as SP3 is a few years in the future ;). Actual 12 servicepack is SP4

### CODE REVIEW

**Comment by PRMerger8** [comment]
@petersatsuse : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@petersatsuse Thank you for catching this! Please remove the **en-us** locale specifier from the URLs you are adding, then we will be OK to merge. Thanks again.

**Comment by PRMerger8** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Looks good @jborsecnik, thanks. #sign-off

**Pull request merged**
