### PR TITLE
Update azure-stack-vm-considerations.md

### PR DESCRIPTION
**Pull request by kivenkat**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kivenkat** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@kivenkat: I'm sorry - only the author of this article, @mattbriggs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger7** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@kivenkat This is the public repo so the author will have to approve and sign off. If you want to sign off yourself, please move it to the private repo.

**Comment by ktoliver** [comment]
Hi @kivenkat - Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules. 

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 

For more information, see [Should I work in a private or a public repo?](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) 

Would you create a pull request in the private repo to make these updates? We'll close this PR. Thank you.

**Pull request closed without merging**
