### PR TITLE
Update host-network-requirements.md

### PR DESCRIPTION
**Pull request by jespli**
HYPER converged solution includes all traffic types (compute, storage, and management)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@jespli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jespli** [comment]
should be "hyperconverged"

**Comment by Jak-MS** [comment]
@dcuomo 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by sethmanheim** [comment]
Closing as the current documentation is accurate: "converged" indicates that all traffic type run on the same adapters. Hyper-Converged is the model of deployment for storage spaces direct (vs disaggregated storage AKA SAN).

**Pull request closed without merging**
