### PR TITLE
Outlining drawbacks of VM creation via WAC or PS on Azure Stack HCI 23H2

### PR DESCRIPTION
**Pull request by Karl-WE**
outlining more actual drawbacks of PowerShell and WAC to create VMs on Azure Stack HCI 23H2. It is not just a manageability feature.

### CODE REVIEW

**Comment by Karl-WE** [comment]
the link should point to https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-arc/choose-service.md
Not sure how to accomplish this correctly. Thanks for resolving this

**Comment by Court72** [comment]
@alkohli

Can you review the proposed changes? Note that the [validation warning](https://github.com/MicrosoftDocs/azure-stack-docs/pull/3207#issuecomment-2197697187) must be resolved before merging.
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
Hello @Karl-WE Thank you for your contribution! We have captured that changes you suggested via a PR against the azure-stack-doc-pr repo: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/15443  and also resolved the warning. The changes should go live over the weekend. Closing this PR. #please-close

**Comment by Karl-WE** [comment]
Thank you!

**Pull request closed without merging**
