### PR TITLE
Update service-plan-offer-subscription-overview.md

### PR DESCRIPTION
**Pull request by KennyLowe**
There is no documentation I can find which notes the security posture enabled by the separation of duties between operator and tenant, this is a particularly powerful capability for service providers, and indeed enterprises where the operator should not be able to access  the contents of tenant subscriptions, and so this should be documented.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@KennyLowe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BryanLa** [comment]
@KennyLowe - thanks much for your contribution.

I've done some research on this. Your suggestion looks good, but I'm wondering if you want to add a final disclaimer sentence, something along the lines of: *“The exception to this case is a situation where the subscription owner is unable to provide the operator access to it, requiring the administrator to take ownership of the subscription as discussed in [Change the billing owner for an Azure Stack Hub user subscription](https://docs.microsoft.com/azure-stack/operator/azure-stack-change-subscription-owner).*

This exception could apply in scenarios where the Azure Stack Hub instance is being managed by a CSP/hoster (access required for troubleshooting, resolving billing issues, etc.), as well as cases where it's management by an enterprise (a scenario where a subscription owner is an employee leaves the company).

**Comment by PRMerger16** [comment]
@KennyLowe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KennyLowe** [comment]
I have added an additional commit containing the suggested text, that makes sense to me! Thanks :)

**Comment by BryanLa** [comment]
@KennyLowe - Sure! Looks great. This should get republished either this afternoon (3pm-ish Pacific), or next Monday morning (10am-ish Pacific). Thanks again.

#sign-off

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
