### PR TITLE
Update deploy-foundational-patterns.md

### PR DESCRIPTION
**Pull request by heoelri**
fixed a broken link

### CODE REVIEW

**Comment by PRMerger8** [comment]
@heoelri : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Looks good. I couldn't test the updated link in GitHub preview, so I changed it to an absolutely link. Thanks @heoelri

**Comment by ktoliver** [comment]
@mattbiggs - Should have asked you to OK this. (PR reviewers are asked to merge PRs that fix typos, formatting issues, broken links that can be verified, etc.) Because the relative link goes to a different repo, I couldn't validate it in GitHub preview, so I changed it to an external link. I also removed extra table column syntax that breaks the table view in GitHub preview.

**Comment by mattbriggs** [comment]
@ktoliver Thanks for letting me know! And thanks for the update.

**Pull request merged**
