### PR TITLE
Update single-server.md

### PR DESCRIPTION
**Pull request by jaromirk**
fixed powershell commands + added deleting and recreating performance history command

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jaromirk : Thanks for your contribution! The author(s) have been notified to review your proposed change. @robess

**Comment by jaromirk** [comment]
@robess here is end-to-end posh script to demonstrate single node deployment and then expansion to 2 node https://github.com/microsoft/MSLab/blob/dev/Scenarios/AzSHCI%20and%20Cluster%20Expansion/Scenario.ps1

**Comment by Court72** [comment]
@ronmiab 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by ronmiab** [comment]
@Court72 - The proposed changes are being reviewed. Once the review is complete, I will comment accordingly.

**Comment by ronmiab** [comment]
#sign-off

**Pull request merged**
