### PR TITLE
Remove Pootle

### PR DESCRIPTION
**Pull request by mdhont**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mdhont : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by mdhont** [comment]
Could this be merged? If there is anything missing please let me know.

**Comment by sethmanheim** [comment]
@mdhont Very sorry for the delay here, thank you again for the contribution. #sign-off

**Pull request merged**
