### PR TITLE
Update azure-stack-network-differences.md

### PR DESCRIPTION
**Pull request by m12net**
Updating reference to vNeet peering introduced in 2008

### CODE REVIEW

**Comment by PRMerger19** [comment]
@m12net : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
close/reopen test build process

**Comment by mattbriggs** [comment]
#sign-off

**Review by mattbriggs — APPROVED** [review]

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
