### PR TITLE
Now AKS on HCI supports up to 8 physical servers

### PR DESCRIPTION
**Pull request by tksh164**
The following blog post mentioned that AKS on HCI supports up to 8 physical servers.

https://techcommunity.microsoft.com/t5/azure-stack-blog/aks-on-azure-stack-hci-november-2021-update/ba-p/2995180
> **Increasing physical node support from 4 nodes to 8 nodes**
> AKS on AzureStack HCI supports deployments on up to 8 physical nodes which makes it easier to run AKS on AzureStack deployments with a wider variety of Azure Stack HCI hardware and to scale up your deployment with confidence.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@tksh164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by mattbriggs** [comment]
@tksh164

Thanks for your feedback. We've updated the content.

https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support

**Comment by mattbriggs** [comment]
#please-close

**Pull request closed without merging**
