### PR TITLE
Adding -lowprivilege usage to csr generation

### PR DESCRIPTION
**Pull request by erskinejohn**
Adding -lowprivilege usage to csr generation

### CODE REVIEW

**Comment by PRMerger4** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@BryanLa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BryanLa** [comment]
@erskinejohn  -  I made a few tweaks on your branch, mostly formatting stuff. Please have a look and LMK if you're OK w/my updates and I can sign this off. Thanks!

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by BryanLa** [comment]
#sign-off

**Pull request merged**
