### PR TITLE
Update ad-sso.md

### PR DESCRIPTION
**Pull request by Elektronenvolt**
The parameter -outputLocation changed to -configPath with release 1.0.0.0

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Elektronenvolt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@lahirisl for review

Thanks.

**Comment by sethmanheim** [comment]
Sorry for the delay on this. 
#sign-off

**Comment by PRMerger14** [comment]
@sethmanheim: I'm sorry - only the author of this article, @lahirisl, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sethmanheim** [comment]
Move to private repo, will make the change there. #please-close

**Pull request closed without merging**
