### PR TITLE
Friendlier az cli output

### PR DESCRIPTION
**Pull request by carmencrincoli**
Let's help the user out. Instead of making them parse the whole JSON response to see if ProvisioningState = Succeeded, just get that one bit of data for them. Much nicer, right? :)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@carmencrincoli : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ManikaDhiman** [comment]
Hi @ZmanKyle: Could you please review this PR? Thanks!

**Comment by ZmanKyle** [comment]
This is a valid update. One more thing that needs to be updated along with this is that in the description above this command. instead of saying "provisioning state is succeeded", we should now say "result is succeeded".

**Comment by ManikaDhiman** [comment]
Hi @carmencrincoli. Thanks for your contribution! Your changes from this PR have been merged and published: https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address.

#please-close

**Pull request closed without merging**
