### PR TITLE
Adding MAC address content from network integration

### PR DESCRIPTION
**Pull request by wamota**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@wamota : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mattbriggs - I updated the metadata title/description to match the new article title. can you take a quick look before I merge this? i also made a few editorial tweaks to match Microsoft style. thanks. #hold-off

**Comment by mattbriggs** [comment]
@Jak-MS Thanks. Would be helpful if we had the ability to update as well. But this is great. :) Thanks for your help! #sign-off

**Pull request merged**
