### PR TITLE
Adding script for VS Code.

### PR DESCRIPTION
**Pull request by sijuman**
@mattbriggs

### CODE REVIEW

**Comment by PRMerger16** [comment]
@sijuman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@mattbriggs: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger10** [comment]
@sijuman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@sijuman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
