### PR TITLE
Arc VM FAQ item add

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @alkohli. Thanks.

**Comment by Jak-MS** [comment]
@alkohli 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
#please-close

**Review by Karl-WE — CHANGES_REQUESTED** [review]
The FAQ need to be more specific on the semantics.

Only Azure Stack HCI Arc VMs are currently free of cost. Refer new guidance on different ways of Azure Arc, added to docs for Arc on 7th of May. 

@alkohli 
Is there another PR in progress. Unclear why this one got closed.

**Pull request closed without merging**
