### PR TITLE
Update azure-stack-release-notes-1904.md

### PR DESCRIPTION
**Pull request by avishwan**
Added an issue with deleting marketplace products

### CODE REVIEW

**Comment by PRMerger15** [comment]
@avishwan : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by avishwan** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@avishwan: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
