### PR TITLE
Adding new known issues

### PR DESCRIPTION
**Pull request by sranthar**
New known issues were uncovered in the recent ICMs, adding these issues for the N-2 known issues release notes

### CODE REVIEW

**Comment by PRMerger17** [comment]
@sranthar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Looks fine, thank you. 
#sign-off

**Comment by sranthar** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@sranthar: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
