### PR TITLE
Updated Max NICs for DS1_v2

### PR DESCRIPTION
**Pull request by ScottNapolitan**
Updated Max NICs for Standard_DS1_v2 to match Azure. This is also what we support.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ScottNapolitan : Thanks for your contribution! The author, @mattbriggs, has been notified to review your proposed change.

**Comment by ScottNapolitan** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ScottNapolitan: I'm sorry - only the author of this article, @mattbriggs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mattbriggs** [comment]
#sign-off

**Pull request merged**
