### PR TITLE
Cloud network vswitch naming

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by Court72** [comment]
@alkohli

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
#sign-off

**Comment by alkohli** [comment]
#please-hold

**Comment by Court72** [comment]
#hold-off

**Review by Karl-WE — CHANGES_REQUESTED** [review]
I am fine with the correction in lines 232-239. The other parts are no easy to understand and do have some issues.

First of all it should be included a disclaimer that NetworkATC is used and we should avoid manual preconfiguration and naming vSwitches and VMNetworkadapters.
The particular settings of the switches might differ from the creation with NetworkATC

**Pull request merged**
