### PR TITLE
Adding known issue for Set-AzKeyVaultAccessPolicy with BypassObjectIdValidation

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@bganapa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@bganapa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bganapa** [comment]
@mattbriggs you should be able to edit the file inplace in the PR for any required changes, if not pls make comments, i will update it. Thanks!

**Comment by bganapa** [comment]
> @bganapa For some reason we don't have permission to edit inline! But I added comments for review. Thanks!

you still need to submit the review :).

**Review by mattbriggs — CHANGES_REQUESTED** [review]

**Comment by mattbriggs** [comment]
@bganapa review submitted...

**Comment by mattbriggs** [comment]
@bganapa I think you have to make the changes? Let me know what you need from me if I am misreading the status.

**Comment by bganapa** [comment]
@mattbriggs I realize that we have this documented in another page and it need not be part of known issue. I am closing this PR. No need to merge

**Pull request closed without merging**
