### PR TITLE
Update plan-volume.md

### PR DESCRIPTION
**Pull request by shsadash0**
S2D does not support traditional file servers, so I want to change it to SoFS.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@shsadash0 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by sethmanheim** [comment]
Fixing in private repo. #please-close

**Comment by PRMerger7** [comment]
Invalid command: '#please-close'. Only Microsoft employees can use this command.

**Comment by sethmanheim** [comment]
#please-close

**Pull request closed without merging**
