### PR TITLE
fix: azure-stack/operator/azure-stack-backup-enable-backup-powershell.md

### PR DESCRIPTION
**Pull request by nschonni**
-  MD019/no-multiple-space-atx
- Trim trailing space
- Space around headers
- certifcate -> certificate

### CODE REVIEW

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @jeffgilb, has been notified to review your proposed change.

**Comment by jeffgilb** [comment]
Hello, I've fixed the typo in a separate PR. the other changes do not affect the published content in meaningful ways.

**Comment by jeffgilb** [comment]
#please-close

**Comment by nschonni** [comment]
@jeffgilb this issues are flagged by markdownlint, which is part of the Docs Authoring pack. Would you prefer I PR something to suppress all errors?

**Pull request closed without merging**
