### PR TITLE
Updating with some of the content from network integration

### PR DESCRIPTION
**Pull request by wamota**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@wamota : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mattbriggs** [comment]
@wamota: Can you resolve your the merge conflict? I think you can do it through the GitHub interface.

**Comment by PRMerger9** [comment]
@GitHubber17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@mattbriggs - The merge conflict is now resolved. Is this request approved for merge? Thanks

**Comment by mattbriggs** [comment]
@GitHubber17 Yes please. #sign-off

**Pull request merged**
