### PR TITLE
Added link to Choosing Arc service doc

### PR DESCRIPTION
**Pull request by johnmarco**

### CODE REVIEW

**Comment by johnmarco** [comment]
#unassign: ManikaDhiman

**Comment by johnmarco** [comment]
#assign: johnmarco

**Comment by johnmarco** [comment]
Hi @ManikaDhiman . I see that you are assigned as the author on the doc I'm working on in this PR. Can you review it please and make sure you're okay with the change? Basically, I am adding a link to a new doc that's been created to help make it easier for customers to decide on what Arc service to choose. Thanks!

**Comment by Court72** [comment]
Hi @johnmarco,

This pull request was opened in the public repo. Content developers should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Pull request closed without merging**
