### PR TITLE
Correction to feature name for SMB Bandwidth Limit

### PR DESCRIPTION
**Pull request by mahoncj**
Role name for "SMB Bandwidth Limit" is actually "FS-SMBBW". Code block will fail unless corrected.

### CODE REVIEW

**Comment by Court72** [comment]
@ronmiab

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ronmiab** [comment]
@Court72 - your message has been received and the change is being reviewed. Once the change is verified, I will do the needful on the sign-off.

**Review by ronmiab — APPROVED** [review]
per the PM, the SMB Bandwidth feature name is "FS-SMBBW". The article has the display name and that needs to be corrected. It should be the feature name as suggested in this PR.

**Comment by ronmiab** [comment]
#sign-off

**Pull request merged**
