### PR TITLE
Update azure-site-recovery.md

### PR DESCRIPTION
**Pull request by shijojoy**

### CODE REVIEW

**Comment by shijojoy** [comment]
To redirect to ASR site

**Comment by shijojoy** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@IngridAtMicrosoft 

- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by shijojoy** [comment]
#sign-off

**Pull request closed without merging**
