### PR TITLE
Update MetalLB configuration steps

### PR DESCRIPTION
**Pull request by josephbath**
Update MetalLB configuration steps:
Newer versions of MetalLB don't support in-line configuration via the Helm values file. MetalLB is now configured using Custom Resources.

### CODE REVIEW

**Comment by josephbath** [comment]
@microsoft-github-policy-service agree [company="Domino's LLC"]

**Comment by Court72** [comment]
@sethmanheim

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by baziwane — APPROVED** [review]
LGTM, thanks!

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
