### PR TITLE
Update azure-stack-get-pki-certs.md

### PR DESCRIPTION
**Pull request by erskinejohn**
Change cmdlet names
Separate New Certificate (deployment) and Renewal (rotation) scenarios.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@erskinejohn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @erskinejohn - Substantial updates to articles should be made in the private repository (azure-stack-docs-pr), which has robust quality validations, a staging environment, and comprehensive PR review. Would you create a PR in the private repo to submit these updates?

To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the repo name in the URL. 

It looks like you haven't worked in the azure-stack-docs-pr repo before. You probably will need to [Join MicrosoftDocs organization and others](https://review.docs.microsoft.com/help/contribute/contribute-get-started-setup-github?branch=master#join-microsoftdocs-organization-and-others) first.

We'll close this PR. If you have any trouble working in the private repo, please let us know and we can reopen this one. Thanks. 

<hr>

Related links in the [internal Microsoft Docs contributor guide](https://review.docs.microsoft.com/help/contribute/?branch=master):

[**Public vs. private repos**](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=master) | [**Move a commit to a different repo (public -> private)**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication) | [**GitHub for content reviews**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-reviews?branch=master)
[**Quick reference for contributing to the docs**](https://review.docs.microsoft.com/help/contribute/contribute-quick-reference?branch=master) | [**Make changes to a Docs article**](https://review.docs.microsoft.com/help/contribute/edit-doc-with-vs-code-and-git-cli?branch=master) | [**PR review quality criteria**](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master)

**Comment by ktoliver** [comment]
@johnerskine Well, it's something to work toward in the future. :)

**Comment by mattbriggs** [comment]
@ktoliver I'll be working on some of @IngridAtMicrosoft for a bit. Do you need me to send a note to techdocprs? Thanks, Matt

**Pull request merged**
