### PR TITLE
Fix #1975

### LINKED ISSUE #1975: Link to Sandbox Guide
Need a link to this guide https://github.com/microsoft/AzStackHCISandbox on this page at the end, as it is currently the best one out there, with minimal issues. Tried the Private Forest guide and the HCI Eval guide, both of those guides have blocking issues right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58cb678-2c81-b3c2-cfce-9ff96c0e18cc
* Version Independent ID: b34bb724-ea12-7063-8d9c-0ff0ae6db190
* Content: [Nested virtualization in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/nested-virtualization)
* Content Source: [azure-stack/hci/concepts/nested-virtualization.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/nested-virtualization.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

### PR DESCRIPTION
**Pull request by jkingdon-ms**
[Fix](https://github.com/MicrosoftDocs/azure-stack-docs/pull/1976/commits/02b986192dd4bf8d303267385dfaa1afe3087ab8) https://github.com/MicrosoftDocs/azure-stack-docs/issues/1975

### CODE REVIEW

**Comment by PRMerger7** [comment]
@jkingdon-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@JasonGerend 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jkingdon-ms** [comment]
#sign-off

**Comment by PRMerger20** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @jasongerend

**Pull request merged**
