### PR TITLE
Update deployment-tool-new-file.md

### PR DESCRIPTION
**Pull request by Iadwan**
updating "You can download the Supplemental Package here:  "

| Azure Stack HCI Supplemental Package component| URL                                             |
|-----------------------------------------------|-------------------------------------------------|
| Bootstrap PowerShell                           | https://go.microsoft.com/fwlink/?linkid=2210545 |
| CloudDeployment.zip                           | https://go.microsoft.com/fwlink/?linkid=2210546 |
| Verify Cloud Deployment PowerShell            | https://go.microsoft.com/fwlink/?linkid=2210608 |

### CODE REVIEW

**Comment by Court72** [comment]
@dansisson 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by dansisson** [comment]
@Iadwan: Please convert this 2-column table to a bulleted list and make the list items hyperlinks (with the URL in the href tag) rather than display the URL explicitly.

**Comment by Iadwan** [comment]
done updated @dansisson

**Comment by dansisson** [comment]
@Iadwan: take a look at your output - these 3 items all run together in a single line. Please copy this:

You can download the Supplemental Package components here:

- [BootstrapCloudDeploymentTool.ps1](https://go.microsoft.com/fwlink/?linkid=2210545)
- [CloudDeployment.zip](https://go.microsoft.com/fwlink/?linkid=2210546)
- [Verify-CloudDeployment.ps1](https://go.microsoft.com/fwlink/?linkid=2210608)

**Comment by dansisson** [comment]
@Iadwan: in the future, please send me the changes/additions you want via email or chat. This will save time on both ends. Thanks.

**Comment by dansisson** [comment]
@Iadwan: this is still all wrong. Please close this PR as I have opened a new one that contains the update and have signed-off and merged to main. It will publish live later this morning. Thank you.

https://review.learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-new-file?branch=pr-en-us-11824

**Comment by ShannonLeavitt** [comment]
Closing per the comment [above](https://github.com/MicrosoftDocs/azure-stack-docs/pull/2141#issuecomment-1405359586).

**Pull request closed without merging**
