### PR TITLE
Migrate VMware

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @alkohli. Thanks.

**Comment by Court72** [comment]
@alkohli

Can you review the proposed changes? Note that these commits must be moved to the private repo for staging and other checks. Let us know if you'd like the PR review team's help moving the commits. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
@dansisson I have already included all these changes into the release-hci-vmware rel branch for Migration. Please close this PR.

**Comment by Karl-WE** [comment]
Excuse me @alkohli, have these changes you have written been merged?

**Pull request closed without merging**
