### PR TITLE
Update for MySQL RP 1.1.47.0

### PR DESCRIPTION
**Pull request by xiaofmao**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@xiaofmao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by xiaofmao** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@xiaofmao: I'm sorry - only the author of this article, @mattbriggs, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
Hi @xiaofmao 

This contribution needs to be made through the private repository so the content can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.

For more information, see [Should I work in a private or a public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master)?

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/fork-and-clone?branch=master).

Once you are working in the private repo, if your update is tied to a specific date and/or time, you'll need to sign off only when the PR is ready to be merged and published. In either repo, we can't hold PRs to merge on a specific date.

Would you create a pull request in the private repo to make these updates? We'll close this PR. Thank you.

**Pull request closed without merging**
