### PR TITLE
Calling out 1904 as express update

### PR DESCRIPTION
**Pull request by PPacentMSFT**
Calling out 1904 as express update

### CODE REVIEW

**Comment by PRMerger20** [comment]
@PPacentMSFT : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@PPacentMSFT Can you please change 1903 to 1904?

For future reference, if you had submitted this PR to the private repo instead of public, I'd be able to make the change for you.

**Comment by sethmanheim** [comment]
#hold-off

**Comment by PRMerger13** [comment]
@PPacentMSFT : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Looks good, thanks. #sign-off

**Pull request merged**
