### PR TITLE
Version mismatch

### PR DESCRIPTION
**Pull request by kojinak**
With an internet connection AzureStack PowerShell = 1.8.0, but Without an internet connection Azure Stack PowerShell = 1.5.0.

### CODE REVIEW

**Comment by ktoliver** [comment]
@justinha Could you review the proposed changes? Thanks.

**Comment by PRMerger10** [comment]
@kojinak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jbpaux** [comment]
Should 1.8.1 for 2002 release

**Comment by ktoliver** [comment]
@justinha Would you review the update to one of your articles? Thanks.

**Comment by sethmanheim** [comment]
@ktoliver Justin is no longer with the team -- we will get the metadata updated, but can we please merge this in the meantime? Thank you!

**Comment by ktoliver** [comment]
@sethmanheim You bet. Thanks for the information and for the review.

**Pull request merged**
