### PR TITLE
OAW2B refresh

### PR DESCRIPTION
**Pull request by peiwentian**
Update expected hashvalue for OAW2B package & change the public link reference

### CODE REVIEW

**Comment by PRMerger20** [comment]
@peiwentian : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
@BryanLa CCing you for your info

**Comment by mattbriggs** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@mattbriggs: I'm sorry - only the author of this article, @PatAltimore, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PatAltimore** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mattbriggs and @PatAltimore - The Docs publishing standard and guidance is to use relative links. Is there a reason relative links shouldn't be used in this case? I added a commit to revert this change. OK or no? Thanks.

**Comment by ktoliver** [comment]
It's known that you can't click through inter-repo relative links in GitHub preview, but you can use the links and test them in preview by adding `docs.microsoft.com` to the left of the relative link. For example, `/azure/storage/common/storage-use-azcopy-v10` becomes https://docs.microsoft.com/azure/storage/common/storage-use-azcopy-v10.

**Comment by mattbriggs** [comment]
@peiwentian Please update your PR with the changes indicated. We use relative links to sites in the docs.microsoft.com. In addition, we if you remove the locale section in the URL, this will enable localization for a reader based on their region. Please remove any locale tags in the URLs. Can you make the updates to your PR and @message me? thanks, Matt

**Comment by mattbriggs** [comment]
@ktoliver Thanks for your review.

**Comment by ktoliver** [comment]
@mattbriggs I already added a commit to revert two revisions to the original relative links. Shall we merge now? Thanks!

**Comment by mattbriggs** [comment]
@ktoliver yes please.

**Comment by peiwentian** [comment]
@mattbriggs @ktoliver Thank you for helping me review the PR. The reason I am trying to modify the link is that the relative link is pointing to the wrong page, it will redirect to the url starting from https://github.com/MicrosoftDocs/** (if you click on the link in the page, it shows 404). Could you please help me understand how I am able to point to the correct page? Thanks!

**Comment by mattbriggs** [comment]
@peiwentian: Kristine noted above: "It's known that you can't click through inter-repo relative links in GitHub preview, but you can use the links and test them in preview by adding docs.microsoft.com to the left of the relative link. For example, /azure/storage/common/storage-use-azcopy-v10 becomes https://docs.microsoft.com/azure/storage/common/storage-use-azcopy-v10."

Our preview site doesn't include an accurate preview of the link experience for relative links. So to validate them you need to, unfortunately, reconstruct the relative link using the instructions above. We require relative links for possible disconnected scenarios for our doc (I believe).

Thanks for asking about this and making sure your links are valid. :)

**Pull request merged**
