### PR TITLE
Update single-server.md

### PR DESCRIPTION
**Pull request by FloKlaffenbach**
Guide not working, you need to install role and feature first.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@FloKlaffenbach : Thanks for your contribution! The author(s) have been notified to review your proposed change. @robess

**Comment by jborsecnik** [comment]
@ronmiab, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged"

**Review by ronmiab — CHANGES_REQUESTED** [review]
The numbering is currently off. Use PowerShell to create a cluster, skipping creating a cluster witness, should be number 4 given the proposed step/change.

**Review by ronmiab — CHANGES_REQUESTED** [review]
@FloKlaffenbach - suggested change per further discussion with PM, please let me know of any questions/feedback.

3. Install roles and features

```powershell
Install-WindowsFeature -Name "BitLocker", "Data-Center-Bridging", "Failover-Clustering", "FS-FileServer", "FS-Data-Deduplication", "Hyper-V", "Hyper-V-PowerShell", "RSAT-AD-Powershell", "RSAT-Clustering-PowerShell", "NetworkATC", "Storage-Replica" -IncludeAllSubFeature -IncludeManagementTools
```

**Comment by ronmiab** [comment]
Created a pull request on the private side with the suggested changes in the last comment.

#please-close

**Pull request closed without merging**
