### PR TITLE
Update deployment-prep-active-directory.md

### PR DESCRIPTION
**Pull request by v-Andre**
Added note that the domain LCM User name cannot be the same name as the local admin user. 

e.g.

domain/myuser
HCI01/myuser

This creates multiple issues in the deployment steps (confirmed for the latest version in lab). 

e.g.

During cluster creation step, it will fail with "Set operating system and version in Active Directory Domain Services. Access is denied."

During "ConfigStorage" of role "Storage", it will fail with "Cannot connect to CIM server. A specified logon session does not exist."

### CODE REVIEW

**Comment by Court72** [comment]
@alkohli

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alkohli** [comment]
@v-Andre Checking with PM. #in-progress

**Comment by alkohli** [comment]
@v-Andre Confirmed with Thomas R. This change is good to go. Signing off. #sign-off

**Comment by alkohli** [comment]
@v-Andre Here is the PR where I pulled your changes: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/16440
Closing this PR. #please-close

**Pull request closed without merging**
