### PR TITLE
Remove Bitnami TestLink

### PR DESCRIPTION
**Pull request by jotamartos**
This application is not maintained anymore by the upstream project and it was removed from the Bitnami catalogue

### CODE REVIEW

**Comment by PRMerger20** [comment]
@jotamartos : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@jotamartos Is that just for the Azure Stack Hub marketplace? It's still listed here in the Azure catalog: https://azuremarketplace.microsoft.com/en-US/marketplace/apps/bitnami.testlink

**Comment by jotamartos** [comment]
Hi @sethmanheim, we also requested the removal of the solution from the Azure's Marketplace. The solution will be removed from there soon.

**Comment by sethmanheim** [comment]
@jotamartos Sounds good, thank you for catching this! #sign-off

**Pull request merged**
