### PR TITLE
Updating a requirement for 22H2

### PR DESCRIPTION
**Pull request by parammahajan5**

### CODE REVIEW

**Comment by parammahajan5** [comment]
#sign-off

**Comment by parammahajan5** [comment]
@dcuomo can you add the comment "#sign-off" to this PR? This is the documentation change we discussed. Thanks

**Comment by Court72** [comment]
@dcuomo 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by sethmanheim** [comment]
@parammahajan5 If you want to sign off on this yourself as well as getting preview links, you should use the private repo.

**Comment by parammahajan5** [comment]
@sethmanheim Ahh, I did not realize this was the non-private repo. Let me close this PR and open one from the private repo. Thanks for spotting that Seth!

**Pull request closed without merging**
