### PR TITLE
TVM overview guidance bullet

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @alkohli. Thanks.

**Comment by Jak-MS** [comment]
@alkohli 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by Karl-WE — CHANGES_REQUESTED** [review]
The livemigration traffic is not encrypted by default but it is signed to ensure SMB tampering through MIM attacks didn’t happen.

Please do not use IPsec. SMB has own encryption capabilities but these are disabled as otherwise RDMA would be not used.

Please contact Ned Pyle (MSFT) for more information.

We are going in circles with this section. IPsec is not suitable.

**Comment by alkohli** [comment]
@Karl-WE  This guidance is coming from the product team. I have asked the PM to take a look at this and respond here before I pull this change into the private repository.

**Comment by alkohli** [comment]
@Karl-WE  Ram Jeyaraman has confirmed that both of you have agreed on this guidance for the moment. I am going to sign off the PR. Thank you for your contribution.


#sign-off

**Pull request merged**
