### PR TITLE
Fix operator access workstation scripts and minor other issues

### PR DESCRIPTION
**Pull request by cblackuk**
Major fix is the `.\` addition as without it the script fails:
image
The rest is mostly cosmetic like trailing spaces, but also there is the double `\\` in a path that I fixed.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@BryanLa – Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by BryanLa** [comment]
@cblackuk - thanks very much for your contribution. I'd like to pull your changes into our internal build system first, just to make sure everything validates/builds correctly. I will get this into our backlog asap.

**Comment by cblackuk** [comment]
Makes sense :-) it should all work hopefully :-)

**Comment by cblackuk** [comment]
Can we get this merged please? :-)

**Comment by BryanLa** [comment]
@cblackuk - yes, apologies, it's in our backlog but hasn't been completed yet. I'll bump it up so it gets done in the next day or so.

#please-close

**Comment by BryanLa** [comment]
@cblackuk - also, please don't delete your branch yet as we'll be pulling it into our internal repo.

**Comment by cblackuk** [comment]
No worries :-) I will leave it be, and thanks again for taking a look at it :-) much appreciate it :-)

**Comment by V-GSOLER** [comment]
@cblackuk This issue has been resolved and will update today at ~ 3:00PM Pacific. Thank you once again for your assist on this.

**Comment by cblackuk** [comment]
Fantastic :-) thank you so much :-)

**Pull request closed without merging**
