### PR TITLE
Removing Azure Update mgmt

### PR DESCRIPTION
**Pull request by carlosmayol**
Removing references to Azure update management and mentioning the dependency agent which is a requirement for service map and also to show to correct configuration of the Azure Monitor integration using WAC

### CODE REVIEW

**Comment by PRMerger16** [comment]
@carlosmayol : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by khdownie — APPROVED** [review]

**Comment by khdownie** [comment]
#sign-off

**Comment by khdownie** [comment]
Hi @ktoliver this says it merged into master but I'm not seeing the changes reflected there.

**Comment by ktoliver** [comment]
Hi @khdownie This pull request was opened in the public repository, so it merged into the instance of master in azure-stack-docs: https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/azure-monitor.md

The update won't be reflected in the instance of master that's in the private repository until the publishing team does a regularly scheduled sync from public repo to private repo. If you need more info about this process, I can email you some links to the internal contributor guide.

Thanks.

**Comment by khdownie** [comment]
Thanks @ktoliver - it sounds like we just need to wait then (which is fine) - do you happen to know how often the sync occurs, or when the next sync will take place?

**Comment by ktoliver** [comment]
@khdownie I'll send you the info on Teams.

**Pull request merged**
