### PR TITLE
Update compare-windows-server.md

### PR DESCRIPTION
**Pull request by cpuck**
Changed 30 day trial to 60 day trial given recent product change.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@cpuck : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@khdownie for review

Thanks.

**Review by JasonGerend — APPROVED** [review]

**Comment by JasonGerend** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@JasonGerend: I'm sorry - only the author of this article, @khdownie, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
