### PR TITLE
Clarified tenant experience on VPN GW assigned IP 

### PR DESCRIPTION
**Pull request by CHDAFNI-MSFT**

### CODE REVIEW

**Comment by sethmanheim** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @sethmanheim - I made some grammar revisions. Could you check that I didn't change the meaning? There might be a more graceful way to say it . . . (I don't know what "reflected" means in a technical sense, so I'll leave it.) Thanks.

**Comment by sethmanheim** [comment]
I think this is fine, thanks @ktoliver. Would be good to have the original submitter approve as well @CHDAFNI-MSFT

**Comment by PRMerger15** [comment]
@CHDAFNI-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks, all! Merging now.

**Pull request merged**
