### PR TITLE
Remove Bitnami multi-tier applications

### PR DESCRIPTION
**Pull request by migruiz4**
Remove the following applications as they have been deprecated by Bitnami:

* Cassandra Cluster
* Elasticsearch Cluster
* etcd Cluster
* Jenkins Cluster
* Kafka Cluster
* MariaDB with Replication
* MariaDB Galera Cluster
* Memcached Multiple Instances
* MongoDB with Replication
* Moodle Multi-Tier
* MySQL with Replication
* NATS Cluster
* PostgreSQL with Replication
* RabbitMQ Cluster
* Redis High Availability
* WordPress Multi-Tier
* ZooKeeper Cluster

### CODE REVIEW

**Comment by migruiz4** [comment]
@microsoft-github-policy-service agree [company="bitnami"]

**Comment by migruiz4** [comment]
@microsoft-github-policy-service agree company="bitnami"

**Comment by Court72** [comment]
@sethmanheim 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by sethmanheim — APPROVED** [review]
@migruiz4 Thank you so much, this looks great. OK to sign off.

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
