### PR TITLE
Update azure-stack-add-vm-image.md

### PR DESCRIPTION
**Pull request by kivenkat**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kivenkat** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@kivenkat: I'm sorry - only the author of this article, @Justinha, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@kivenkat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Validation checks seem to be stalled. Will try close/reopen.

**Comment by ktoliver** [comment]
@Justinha - For a future update, line 57 is missing a word. I don't know the correct procedure to document (stop and deallocate or stop or deallocate).

**Comment by kivenkat** [comment]
It’s actually just stop deallocate (Azure terminology)  @Justin Hall<mailto:Justin.Hall@microsoft.com>

**Pull request merged**
