### PR TITLE
AZ marketplace media folder rename

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by dansisson** [comment]
THIS IS A DRAFT

**Comment by Jak-MS** [comment]
@dansisson 

- consider putting the PR [into draft mode ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) until it's ready to review. Triage (what I am doing now) will still happen, but reviewers will know it's not ready. Up to you of course.
- when this is ready for review, tag @alkohli and @ManikaDhiman so they can review it

@alkohli @ManikaDhiman - when this is ready (and approved for merge), can you add `#sign-off` in a comment? Thanks.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@ManikaDhiman @dansisson - merging this. please make sure to check the live page after the changes are published to confirm that the images are displaying as intended. thanks

As in the other PR, this screenshot - `media/virtual-machine-image-azure-marketplace/deployment-in-progress.png` contains a Correlation ID. I'm not clear on if that's PII or not, but if it is, please mask it in a follow-up PR. thanks

**Pull request merged**
