### PR TITLE
Update vm-powershell.md - replaced get-clustergroup

### PR DESCRIPTION
**Pull request by Karl-WE**
code issue fixed in l164, replaced get-clustergroup

related to issue #2301 
As Jason did not respond, we can spare his participation for this minor change. Basically a typo or Ctrl+V one.

Thanks for signoff @alkohli

### CODE REVIEW

**Comment by Court72** [comment]
@JasonGerend

Can you review this PR? Sign off or approve if you accept the changes.

**Note**: To sign off, add a `#sign-off` comment to the PR.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Karl-WE** [comment]
Hi @JasonGerend do you concur with the fix? Thanks for sign-off.

**Comment by Court72** [comment]
@karl-we, @alkohli,

I resolved the merge conflict in this PR, and the updates no longer apply. If the article still needs attention, can you open a new PR? Thanks.

**Comment by Karl-WE** [comment]
Thank you @Court72 I have reviewed the latest and raised a new PR #3206 as per your request.

**Pull request closed without merging**
