### PR TITLE
Update azure-stack-release-notes-known-issues-1905.md

### PR DESCRIPTION
**Pull request by efemmano**
Added marketplace management known issue

### CODE REVIEW

**Comment by PRMerger6** [comment]
@efemmano : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by efemmano** [comment]
# signoff

**Comment by efemmano** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@efemmano: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sethmanheim** [comment]
Looks fine, thank you. 
#sign-off

**Comment by PRMerger15** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
