### PR TITLE
Added DNS name label info

### PR DESCRIPTION
**Pull request by ScottNapolitan**
Added details for DNS Name  label delegation. @sethmanheim for approval.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ScottNapolitan : Thanks for your contribution! The author, @jeffgilb, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@sethmanheim : Thanks for your contribution! The author, @jeffgilb, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @ScottNapolitan - thanks for submitting these suggested changes. I've assigned to the article's author  @sethmanheim to review them.  

Just an FYI, Microsoft PMs and content pros should be using the private repos for making content changes. Can you use the private repo next time?

Thanks.

***
For future reference:
Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by sethmanheim** [comment]
Looks good, thank you! #sign-off

**Comment by PRMerger16** [comment]
@sethmanheim: I'm sorry - only the author of this article, @jeffgilb, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
