### PR TITLE
Change documentation to Allow Cluster Administrator network firewall …

### PR DESCRIPTION
**Pull request by yupsez**
…exceptions from TCP 137 to UDP 137.

Under the section Failover Clustering.
The protocol type needs be changed from Current TCP to UDP as shown here https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements.

From 
Rule	Action	Source	Destination	Service	Ports
Allow Cluster Administrator	Allow	Management system	Cluster servers	TCP	137

Change this to 
Allow Cluster Administrator	Allow	Management system	Cluster servers	UDP	137

### CODE REVIEW

**Comment by Court72** [comment]
@ManikaDhiman 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
Hi @Court72: I've reached out to the product team to review the proposed changes. I'll update this PR as soon as I hear anything back. Thanks!

**Comment by ManikaDhiman** [comment]
The product team confirmed that the changes are good.


#sign-off

**Comment by ManikaDhiman** [comment]
Hi @Court72: The changes are good here. Could you please sign off this PR? I can't do it because I am not the listed author. Thanks!

**Pull request merged**
