### PR TITLE
Updating ms.topic and ms.prod for the HCI-related content

### PR DESCRIPTION
**Pull request by eross-msft**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@eross-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by eross-msft** [comment]
@iainfoulds FYI
This is an update to the ms.topic and ms.prod metadata of the Azure Stack HCI-related content, to include the how-to and troubleshooting values. It looks like there are some spacing adjustments that came along from the update from master.

#sign-off

**Comment by PRMerger7** [comment]
@eross-msft: I'm sorry - only the author of this article, @khdownie, @v-dasis, @davannaw-msft, @jasongerend, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @eross-msft This PR was opened in the public repo. Would you close this PR and submit the updates in a PR in the private repo? To cut down on the work of re-creating the edits in each file in the private repo, you could follow the steps in [Pull public commits to the private repo for updates, staging, publication](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication). Thanks.

**Comment by eross-msft** [comment]
@ktoliver Sorry about that, must've cloned the wrong version. Let me try that again...

**Pull request closed without merging**
