### PR TITLE
Update container-registry-troubleshoot-md.

### PR DESCRIPTION
**Pull request by domggarrity**
Add more info on troubleshooting quota-related issues. Make verbiage and formatting more consistent.

### CODE REVIEW

**Comment by domggarrity** [comment]
#sign-off

**Comment by Court72** [comment]
@sethmanheim 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by sethmanheim** [comment]
@domggarrity Is it possible to move this to the private repo?

**Comment by domggarrity** [comment]
@sethmanheim Sorry, I'm not sure what you mean. Should changes be pushed to a private repo instead of MicrosoftDocs?

**Comment by sethmanheim** [comment]
> @sethmanheim Sorry, I'm not sure what you mean. Should changes be pushed to a private repo instead of MicrosoftDocs?

Can you please use the same repo you used for your previous PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/10839. Thanks!

**Comment by domggarrity** [comment]
@sethmanheim Done. Here is the new PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/11301. Apologies for not originally doing that.

**Comment by sethmanheim** [comment]
> @sethmanheim Done. Here is the new PR: [MicrosoftDocs/azure-stack-docs-pr#11301](https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/11301). Apologies for not originally doing that.

Awesome, thank you!

**Pull request closed without merging**
