### PR TITLE
Add cleanup instructions

### PR DESCRIPTION
**Pull request by jirenugo**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@jirenugo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@jirenugo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@jirenugo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jirenugo** [comment]
@v-susbo , can you please take a look at this?

**Comment by ktoliver** [comment]
@v-susbo for review

Thanks.

**Comment by v-susbo** [comment]
@ktoliver Hi Kristine, I'll review your updates, but we usually use the private repo, azure-stack-docs-pr, for content updates and not the public one, azure-stack-docs. Was there a reason to use the public repo?

**Comment by v-susbo** [comment]
@ktoliver It was easier to edit the topic itself, so I created this PR that you just need to merge: https://github.com/jirenugo/azure-stack-docs/pull/2
Thank you!

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
