### PR TITLE
Minor phrasing updates to LLDP section

### PR DESCRIPTION
**Pull request by dcuomo**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@dcuomo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JasonGerend — APPROVED** [review]

**Comment by JasonGerend** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@JasonGerend: I'm sorry - only the author of this article, @v-dasis, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by v-dasis** [comment]
#sign-off

**Pull request merged**
