### PR TITLE
Fix code blocks

### PR DESCRIPTION
**Pull request by tksh164**
- Fixed hyphen characters in code blocks.
- Fixed a line break in a code block.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@tksh164 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by JasonGerend — APPROVED** [review]

**Comment by JasonGerend** [comment]
Looks great - thanks for making these fixes!!! :) #sign-off

**Comment by PRMerger8** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @ronmiab

**Comment by ronmiab** [comment]
@JasonGerend - thank you for the additional check and reply :). #sign-off

**Pull request merged**
