### PR TITLE
fixing bug

### PR DESCRIPTION
**Pull request by ihcherie**
https://msazure.visualstudio.com/One/_workitems/edit/5992862

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ihcherie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ihcherie** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ihcherie: I'm sorry - only the author of this article, @sethmanheim, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by sethmanheim** [comment]
Moved to the private repo so it gets merged quicker. #please-close

**Pull request closed without merging**
