### PR TITLE
Update firewall-requirements.md added proxy for Arc Integration

### PR DESCRIPTION
**Pull request by steveswalwell**
EMEA FastTrack doc-a-thon - added steps enable proxy use during Cluster Registration and Arc Integration as Arc Integration is now enable by default

### CODE REVIEW

**Comment by Court72** [comment]
@ManikaDhiman 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
@tiaramathur: Could you please review this update for technical accuracy and let me know if it should be added to the Firewall requirements article? Thanks!

**Comment by sethmanheim** [comment]
Since this is the public repo, please be careful about the information you include here, as it's visible publicly.

**Comment by ManikaDhiman** [comment]
Including [danielleemsft](https://github.com/danielleemsft) to review the proposed changes in this PR. Thanks!

**Comment by alkohli** [comment]
@steveswalwell Your suggested changes were incorporated in the article and the changes are now live at this location: [Configure proxy settings for Azure Stack HCI - Azure Stack HCI | Microsoft Learn](https://learn.microsoft.com/en-us/azure-stack/hci/manage/configure-proxy-settings)

**Comment by alkohli** [comment]
Closing this PR. #please-close

**Pull request closed without merging**
