### PR TITLE
Update known-issues.md

### PR DESCRIPTION
**Pull request by xizhuang**
https://supportability.visualstudio.com/Azure%20Stack%20Hub/_workitems/edit/72769

### CODE REVIEW

**Comment by Jak-MS** [comment]
@xizhuang - can you agree to the CLA? See the instructions here: https://github.com/MicrosoftDocs/azure-stack-docs/pull/3394#issuecomment-2468657907 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by xizhuang** [comment]
@microsoft-github-policy-service agree company="Microsoft"


Best Regards,
Xiaoyu Zhuang
Support Escalation Engineer Azure Stack Hub
Customer Support
+86 (21) 52638388
Working Hours: M-F 9:00am - 5:30pm GMT+8

Manager: Donnie Zhang ***@***.******@***.***>
Can't reach me? Contact Azure Stack HUB CSS Backup ***@***.******@***.***>
[MSFT_logo_Gray DE sized SIG1.png]

**Comment by xizhuang** [comment]
Hi Jak,

I have reply the email and agree to CLA.

Thank you

Best Regards,
Xiaoyu Zhuang
Support Escalation Engineer Azure Stack Hub
Customer Support
+86 (21) 52638388
Working Hours: M-F 9:00am - 5:30pm GMT+8

Manager: Donnie Zhang ***@***.******@***.***>
Can't reach me? Contact Azure Stack HUB CSS Backup ***@***.******@***.***>
[MSFT_logo_Gray DE sized SIG1.png]

**Comment by Court72** [comment]
@sethmanheim 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

**Comment by sethmanheim** [comment]
#sign-off

**Pull request merged**
