### PR TITLE
Update system-requirements.md

### PR DESCRIPTION
**Pull request by mkostersitz**
Added static IP address information to the pre-requisite section. @dineshgovindasamy  please review and sign off before merging

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mkostersitz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
close/reopen for build error

**Comment by ktoliver** [comment]
@sethmanheim @mattbriggs - I don't recognize the build error that's occurring in this PR. I don't see it in any PRs in the azure-stack-docs repo. Shall I file a bug, or does someone on your team want to look into it? Thanks.

**Comment by sethmanheim** [comment]
@mattbriggs Matt, this looks possibly related to the GitHub action you were working on last Friday?

**Comment by mattbriggs** [comment]
@sethmanheim @ktoliver Ah ... another unexpected thing. Yes I think this is related. This PR mus have been opened when their was a github action, and then I deleted it, and now it is attempting to fire the action when it doesn't exist.

**Comment by mattbriggs** [comment]
@sethmanheim @ktoliver  from @BryanLa :  This errror may because the contributor pulled from the repo when the workflow existed. It is now gone. And so the failure of the workflow isn't about the PR. The contributor could refresh their branch against master (and this may clear it up) or if the PR is passing review, the workflow error can be disregarded.

**Comment by BryanLa** [comment]
@ktoliver - as @mattbriggs explained above, the "Greetings" check is failing because it no longer exists. It was likely caused by the repo getting forked (and `mkostersitz:patch-1` created) during the short period where the GH action existed. This all happens automatically behind the scenes when the Edit feature is used.

As such, the failing "Greetings" check above can be ignored. The PR still needs review by @dineshgovindasamy and @abhilashaagarwala, but once those are done it can be safely merged.

**Comment by ktoliver** [comment]
> As such, the failing "Greetings" check above can be ignored. The PR still needs review by @dineshgovindasamy Dinesh Kumar Govindasamy FTE and @abhilashaagarwala Abhilasha Agarwala FTE, but once those are done it can be safely merged.

@BryanLa Got it; thanks.

**Comment by ktoliver** [comment]
The article has been updated with some of the content that's added in the pull request, but I can't tell how closely. @dineshgovindasamy and @abhilashaagarwala Could you review the pull request and let us know if it still needs to be merged (after merge conflicts are resolved, if that's possible; the conflicts are fairly complex). Thanks.

**Comment by abhilashaagarwala** [comment]
This does not need to be merged anymore. Please delete this pull request.

**Pull request closed without merging**
