### PR TITLE
Adding additional details for stretch S2D

### PR DESCRIPTION
**Pull request by dcuomo**
@v-dasis - FYI

### CODE REVIEW

**Comment by PRMerger9** [comment]
@dcuomo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-dasis** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@dcuomo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @dcuomo and @v-dasis - I'm not finding the image that's referenced in the update (stretched-storage-spaces-direct.png) either in the pull request or in the repository:

image

Should the image be added to the PR or would you like to remove the image reference? 

Thanks.

**Comment by ktoliver** [comment]
@dcuomo It looks like you've worked in the private repo before. Would you submit this update in a pull request in the private repo? You can add the image then. We'll close this pull request. Thanks.

**Pull request closed without merging**
