### PR TITLE
Local Share media folder rename

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @ManikaDhiman or @alkohli. Thanks.

**Comment by dansisson** [comment]
IN DRAFT - DON'T REVIEW

**Comment by Jak-MS** [comment]
@dansisson - when this is ready for review, can you take it out of draft mode and tag @ManikaDhiman and @alkohli in a comment? thanks!


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
#sign-off

**Pull request merged**
