### PR TITLE
ARM template deployment updates

### PR DESCRIPTION
**Pull request by dansisson**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@alkohli 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by dansisson** [comment]
** THIS IS NOT READY TO REVIEW YET **

**Comment by dansisson** [comment]
If this PR needs approval, or if the commits need to be pulled into the private repo, contact @alkohli. Thanks.

**Comment by alkohli** [comment]
@dansisson  Please close this PR. I have drastically modified the article since this then. This info is now stale.

**Pull request closed without merging**
