### PR TITLE
Deprecate Spree

### PR DESCRIPTION
**Pull request by Mauraza**
Remove Spree since this product has been deprecated by Bitnami.
Signed-off-by: mauraza <gibone@vmware.com>

### CODE REVIEW

**Comment by Court72** [comment]
@Mauraza 

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/azure-stack-docs/pull/2127#issuecomment-1384327012)? After the CLA is signed, someone can review your pull request. Thanks!

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Mauraza** [comment]
@microsoft-github-policy-service agree [company="{vmware}"]

**Comment by sethmanheim** [comment]
I believe there are some merge conflicts here due to conflicts with another external PR that removed all Bitnami items. If that's not the case, please reopen. #please-close

**Comment by Mauraza** [comment]
Hi @sethmanheim,

I want to remove another item Spree. Please reopen de PR.

**Comment by sethmanheim** [comment]
> Hi @sethmanheim,
> 
> I want to remove another item Spree. Please reopen de PR.

Done. Please fix the merge conflicts.

**Comment by sethmanheim** [comment]
Thank you and sorry for the delay! #sign-off

**Pull request merged**
