### PR TITLE
Fix cmdlet name as it is missing a verb

### PR DESCRIPTION
**Pull request by cblackuk**
The cmdlet name is missing a verb.
This will resolve the issue.
Cmdlet is from -> https://www.powershellgallery.com/packages/Microsoft.AzureStack.ReadinessChecker/1.2100.1963.864/Content/CertificateValidation%5CMicrosoft.AzureStack.PublicCertificateRequest.psm1

Also fixed some trailing spaces.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@BryanLa 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
@cblackuk - good catch and thanks for the contribution.

#sign-off

**Comment by cblackuk** [comment]
Wow, thanks a lot :-) that was quick!!!

**Pull request merged**
