### PR TITLE
changing FullLanguageMode to FullLanguage as mode is not a valid option

### PR DESCRIPTION
**Pull request by cblackuk**
Based on:

https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-register?view=azs-2005
and
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-5.1

FullLanguageMode is not a valid option. Fixing to be in line with ASDK doc and to be correct.
Also:
image

### CODE REVIEW

**Comment by PRMerger12** [comment]
@cblackuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @IngridAtMicrosoft - PRMerger automatically assigns pull requests in this repo to the author that's listed in the article metadata. If you're not the right person to review the pull request, could you let us know who would be better able to review it? Thanks.

I'll assign it to @femila for now.

**Comment by cblackuk** [comment]
Can we merge this please? :-)

**Comment by ktoliver** [comment]
@IngridAtMicrosoft @femila Would you review this community contribution to the Azure Stack content? 

Thanks.

**Comment by sethmanheim** [comment]
@cblackuk @ktoliver I'll take this one, it's really not assigned to the right writer. I can #sign-off or pull the commits into the private repo, whichever is easiest.

**Comment by PRMerger14** [comment]
@sethmanheim: I'm sorry - only the author of this article, @IngridAtMicrosoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@sethmanheim: I'm sorry - only the author of this article, @IngridAtMicrosoft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by cblackuk** [comment]
Thanks @sethmanheim :-)

**Comment by ktoliver** [comment]
@sethmanheim Sign-off works. Thanks for the review. I'll merge now.

**Comment by ktoliver** [comment]
@cblackuk I would expect the update to be live later today. Thanks for contributing to the documentation.

**Pull request merged**
