### PR TITLE
Add Clarification for VMIP_1 and VMIP_2 

### PR DESCRIPTION
**Pull request by igomaa**
during the deployment , if this IPs for the VMs not in an ascending order the deployment fails with error Could not find an available address in IP pool of type VM ,  it seems to be excepting a starting IP  and ending IP on for a pool and obviously the starting IP has to be lower than the ending IP

### CODE REVIEW

**Comment by Jak-MS** [comment]
@ManikaDhiman 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ManikaDhiman** [comment]
Hi @ZmanKyle: Could you review this PR for technical accuracy? There are a few typos that must be fixed before merging. Thanks!

**Comment by ZmanKyle** [comment]
@ManikaDhiman The comment here is technically accurate.

**Comment by ManikaDhiman** [comment]
@ZmanKyle: Thanks for the review!

@igomaa: Thanks for your contribution. I have replicated these changes in a private repo PR and merged them--changes will be live after the next publishing pass. Thanks!

#please-close

**Pull request closed without merging**
