### PR TITLE
Add known issue with ConvertTo-AzureRmVMManagedDisk 

### PR DESCRIPTION
**Pull request by cblackuk**
As discussed with MSFT support ConvertTo-AzureRmVMManagedDisk is not support on Azure Stack but it will result in breaking your VM.

Due to this sad fact, I think it is important we warn our customers about it as this came from a customer of mine who wanted to do said conversion and we went for the aforementioned command first.

Internal Bug from MSFT Support (Ref: 1540556) to help you verify it.

I hope I put the reference links correctly to the user documentation but I might have done it wrong... so would appreciate some help here :)

### CODE REVIEW

**Comment by PRMerger10** [comment]
@cblackuk : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@cblackuk : Thanks for your contribution! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@jborsecnik Why didn't I get a chance to review and sign off on this one?

**Comment by jborsecnik** [comment]
@sethmanheim, I merged it by accident. I added a comment, but apparently the comment didn't "stick" in the PR after the merge. I had a note to follow up in case that happened. My comment was this: "Can you review the changes now? If the changes are NOT okay, I will submit a PR to revert them."

I apologize for the error. Let me know if you want me to revert the changes.

**Comment by sethmanheim** [comment]
@jborsecnik No problem, I will check with the PM team to make sure this addition is accurate, and remove it if it isn't. Thank you!

**Comment by jborsecnik** [comment]
Thanks!

**Pull request merged**
