### PR TITLE
Update app-service-billing-faq.md

### PR DESCRIPTION
**Pull request by lpassig**
Mentioning that the default provider subscription is being billed.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@lpassig : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Justinha** [comment]
@apwestgarth Hi, if this is ok to merge can you add #sign-off?

**Comment by PRMerger8** [comment]
@Justinha: I'm sorry - only the author of this article, @apwestgarth, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by apwestgarth** [comment]
#sign-off

**Pull request merged**
