### PR TITLE
Marketplace differences based on Cloud environment

### PR DESCRIPTION
**Pull request by CHDAFNI-MSFT**
Replicating a Note from the 'Download Marketplace items to Azure Stack Hub' page as it relates to marketplace differences

### CODE REVIEW

**Comment by PRMerger16** [comment]
@CHDAFNI-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@sethmanheim I've added a basic introductory sentence per the internal quality criteria ("The article contains an introductory paragraph"), and to give context to the note. Is this OK to merge?

**Comment by sethmanheim** [comment]
@ktoliver Perfect, thanks so much for catching that! OK to sign off. 
#sign-off

**Pull request merged**
